### ISSUE TITLE
Realtime database SetValue Future never completes

### ISSUE THREAD

**Issue by deekay42** [firebase/firebase-cpp-sdk#109]
**EDIT**: I tried to run the quickstart-cpp database testapp and it fails as well.
```Initialized Firebase App.
Initialize Firebase Auth and Firebase Database.
Attempt to initialize Firebase Auth.
Attempt to initialize Firebase Database.
Successfully initialized Firebase Auth and Firebase Database.
WARNING: Persistence is not currently supported.
Auth: Signed in anonymously.
URL: https://testproject-e881a.firebaseio.com/test_app_data/-MDy62gVjP503BviBOGF
TEST: Set simple values.
```
The log stops there.
Again, the futures don't complete.
So that should rule out any errors in code. I think the only thing that's left is my internet connection/firewall.
My understanding is that the database uses https on port 443, however other SSL applications work fine.
Could it be an expired SSL certificate or something? What else happens under the hood, how is the connection established? Do I need to open/forward any ports? 
Is the future thread is never started perhaps? Is  there a deadlock? Am I running in single threaded mode and need to switch to multithreaded?
This would all be much easier if there was an actual error message.

**EDIT2**:
I tethered my phone to my laptop and used my LTE data connection. Everything works like a charm. So clearly my internet connection is to blame here. Again, it would be helpful to know the specifics of the firebase connection protocol to see where it breaks exactly.

**EDIT3**:
The REST api works fine as well.
Both these requests execute successfully and the data shows up in the console.
curl -X POST -d '{"user_id" : "jack", "text" : "Ahoy!"}' 'https://testproject-e881a.firebaseio.com/users/jack/name.json'
curl -X PUT -d '{ "first": "Jack", "last": "Sparrow" }' 'https://testproject-e881a.firebaseio.com/users/jack/name.json'

### Please fill in the following fields:
Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: **Pre-built**
Firebase C++ SDK version: **6.15.1**
Firebase plugins in use (Auth, Database, etc.): **database, auth, app, firestore, messaging, functions**
Additional SDKs you are using (Facebook, AdMob, etc.): **n/a**
Platform you are using the C++ SDK on (Mac, Windows, or Linux): **Windows 10**
Platform you are targeting (iOS, Android, and/or desktop): **desktop**

### Please describe the issue here:

I'm trying to write some data to my realtime database using SetValue. However, the future returned by SetValue never completes and the data is not written. The weird thing is that this is intermittent - it used to work reliably but after switching my work location and upgrading from 6.15.0 to 6.15.1 it only works sometimes. Super weird. Looking at the firebase console I see that this has nothing to do with permissions because no requests are received. Here's my code

  ```
database->set_log_level(firebase::kLogLevelDebug);
  firebase::database::DatabaseReference myRef =
      database->GetReference().Child("uids");
  std::string key = myRef.PushChild().key();
  auto future = myRef.Child(key).Child("uid").SetValue("waiting");
  future.OnCompletion([](const firebase::Future< void >& completed_future,
                       void* user_data) {
    if (completed_future.error() == 0) {
      LogMessage("FUTURE COMPLETED");
    }
    else {
      LogMessage("Error %d: %s",
               completed_future.error(),
               completed_future.error_message());
    }
  }, nullptr);
  ProcessEvents(5000);
```

This code does not print anything and no value gets written which makes it difficult to debug. Initially I thought it might be my internet connection but it appears the future never completes at all. Maybe it is my internet connection, I don't know how to debug this.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ?
Haven't tried it yet, will do asap though.

What's the issue repro rate? 9/10

**Comment by chkuang-g** [comment]
@deekay42 

Firebase Realtime Database is using [WebSocket](https://en.wikipedia.org/wiki/WebSocket) protocol, which is using 443 port for ssl connection but not running HTTP protocol after the initial handshake. 

Is it possible that your wireless router block non-HTTP communication at port 443?  Could you try to disable the Firewall on your PC and your router and try it again.

As Wikipedia stated 
```
Some proxy servers are transparent and work fine with WebSocket; others will prevent WebSocket from working correctly, causing the connection to fail.
```
