### ISSUE TITLE
[Question] Error when building for iOS, MacOS - Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by xuanloct4** [firebase/firebase-cpp-sdk#1096]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: _____
  * Firebase C++ SDK version: _____
  * Main Firebase Components in concern: __Firebase Analytics___ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: ___Mac__ (Mac, Windows, or Linux)
  * Platform you are targeting: __iOS___ (iOS, Android, and/or desktop)

### [REQUIRED] Please describe the question here:
I am building a sample Qt project for iOS that uses Firebase-cpp-sdk.
I added the sdk to CMakeLists.txt as follow
```
set(FIREBASE_CPP_SDK_DIR, "${CMAKE_SOURCE_DIR}/extensions/firebase_cpp_sdk")
add_subdirectory(extensions/firebase_cpp_sdk)
target_link_libraries(${PROJECT_NAME} PUBLIC firebase_analytics)
target_link_libraries(${PROJECT_NAME} PUBLIC firebase_app)
```
But it gives me the error when building the project
```
libfirebase_app.a(app_ios.mm.o):-1: error: Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRConfiguration", referenced from:
      objc-class-ref in libfirebase_app.a(app_ios.mm.o)
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in libfirebase_app.a(app_ios.mm.o)
  "_OBJC_CLASS_$_FIROptions", referenced from:
      objc-class-ref in libfirebase_app.a(app_ios.mm.o)
```

The same issue happens when building the project for MacOS.
Any help, thanks in advance.

**Comment by chkuang-g** [comment]
@xuanloct4 

Those missing references are from Firebase iOS SDK. I think there are two scenario here:

1. Build for iOS app: I think you might miss the Podfile like [this](https://github.com/firebase/quickstart-cpp/blob/main/analytics/testapp/Podfile).  Add it to your Xcode project and run `pod repo update; pod install` and use the generated `.xcworkspace` to build the app.
2. Build for macOS application: In this case, Firebase C++ SDK is not using pods but has its own desktop implementation.  In this case, you will need to configure your CMakeList.txt properly. See [this example](https://github.com/firebase/quickstart-cpp/blob/main/analytics/testapp/CMakeLists.txt)

Please take a look of our samples `readme.md` for reference.
https://github.com/firebase/quickstart-cpp/tree/main/analytics/testapp#building-and-running-the-testapp

Please let me know if this helps!

Shawn

**Comment by xuanloct4** [comment]
> @xuanloct4
> 
> Those missing references are from Firebase iOS SDK. I think there are two scenario here:
> 
> 1. Build for iOS app: I think you might miss the Podfile like [this](https://github.com/firebase/quickstart-cpp/blob/main/analytics/testapp/Podfile).  Add it to your Xcode project and run `pod repo update; pod install` and use the generated `.xcworkspace` to build the app.
> 2. Build for macOS application: In this case, Firebase C++ SDK is not using pods but has its own desktop implementation.  In this case, you will need to configure your CMakeList.txt properly. See [this example](https://github.com/firebase/quickstart-cpp/blob/main/analytics/testapp/CMakeLists.txt)
> 
> Please take a look of our samples `readme.md` for reference. https://github.com/firebase/quickstart-cpp/tree/main/analytics/testapp#building-and-running-the-testapp
> 
> Please let me know if this helps!
> 
> Shawn

Do you mean that for iOS, besides the firbase-cpp-sdk, we also need the firebase framework through Cocoapod?

**Comment by cynthiajoan** [comment]
Correct. In recent [release notes](https://firebase.google.com/support/release-notes/cpp-relnotes) we start to add the iOS dependent Cocoapods version.

**Comment by xuanloct4** [comment]
Sorry for the late reply,

I have already tried the solution as [chkuang-g](https://github.com/chkuang-g) suggestion.
And successfully got it compiled for iOS.
But compiling for the macOS still got the same error. I am using MacOS 11.5.2 (Big Sur).
Any help is appreciated.

**Comment by DellaBitta** [comment]
Hi @xuanloct4,

As chkuang-g mentioned our build process for macOS is different than iOS. Our macOS buids don't use podfiles, which leverages the Firebase iOS SDK, but instead uses our own desktop implementation. [Information on how to build against the desktop implementation can be found here](https://firebase.google.com/docs/cpp/setup?platform=ios#desktop-workflow).
