### ISSUE TITLE
[Question] Undefined symbols, no matter what I build

### ISSUE THREAD

**Issue by PaTiToMaSteR** [firebase/firebase-cpp-sdk#1177]
I bet this might be easy to solve as pre-built libraries works, just target macOS 12 which is to high in Unreal Engine 5.

### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: my issue with pre-built SDK is that target macOS 12, for Unreal Engine I need 10.15
  * Firebase C++ SDK version: I tried 9.4.0 and 10.3.0
  * Main Firebase Components in concern: All
  * Other Firebase Components in use: No code issues
  * Platform you are using the C++ SDK on: Mac, Windows, or Linux
  * Platform you are targeting: All

### [REQUIRED] Please describe the question here:
No matter what I build, manually building I get undefined symbols everywhere.

Nothing fancy here... building from MacOS Ventura
cmake version 3.25.1
```
cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.15"
cmake --build . -- -j$(sysctl -n hw.ncpu) 

```
Some screenshots
<img width="1353" alt="Screenshot 2022-12-25 at 09 15 46" src="https://user-images.githubusercontent.com/3490937/209461381-27799260-69e4-4818-99d2-f976f53f0f8c.png">
<img width="1391" alt="Screenshot 2022-12-25 at 09 15 35" src="https://user-images.githubusercontent.com/3490937/209461385-939bc56e-217f-455d-b3bd-783d5faf3b87.png">

I wonder if the root of all of this is your external download and compilation of curl:
<img width="1228" alt="Screenshot 2022-12-25 at 09 18 22" src="https://user-images.githubusercontent.com/3490937/209461397-771fb89f-2d7f-4ce8-9579-31b21ec8387b.png">

**Comment by DellaBitta** [comment]
Hi @PaTiToMaSteR,

Those libcurl errors are expected as we see them in our own internal CI builds. I believe that the curl source files process-out the definitions of functions in certain source files based on the configuration built, and some resulting object files simply don't have anything in them to link against.

By the looks of the link errors, they seem to be things that reside in `libfirebase_app.a` and `liblibuWS.a`

Could you run `lipo -info <path_to_whichever_lib>` to ensure that it includes both of your target architectures? If so, could you run `nm` on the libraries (for example `nm -S <path_to_whichever_lib>`) to see if you can spot the symbols in question, and if they have a definition in the library, or if they're marked as `U` for undefined?

Thanks!

**Comment by PaTiToMaSteR** [comment]
I’m back again on MacOS making the build I’ll post the info, sorry for my late reply!

**Comment by PaTiToMaSteR** [comment]
Architectures in the fat file: libfirebase_admob.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_analytics.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_app.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_app_check.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_auth.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_database.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_dynamic_links.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_firestore.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_functions.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_gma.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_installations.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_messaging.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_remote_config.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_rest_lib.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_storage.a are: x86_64 arm64 

[symbols.txt](https://github.com/firebase/firebase-cpp-sdk/files/10450159/symbols.txt)

seems to be ok my custom build with macOS 12, I'll re-target to 10.15 and print it again (which is the one giving problems)

**Comment by PaTiToMaSteR** [comment]
cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.15"
cmake --build . -- -j$(sysctl -n hw.ncpu)

lipo -info *
Architectures in the fat file: libFirebaseAuthInterop.a are: x86_64 arm64 
Architectures in the fat file: libFirebaseCore.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_admob.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_analytics.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_app.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_app_check.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_auth.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_database.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_dynamic_links.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_firestore.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_functions.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_gma.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_installations.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_messaging.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_remote_config.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_rest_lib.a are: x86_64 arm64 
Architectures in the fat file: libfirebase_storage.a are: x86_64 arm64 

➜  universal_10.15 nm -S * > symbols.txt                                                                                                                                                
thread_pthread.cc.o: no symbols
hard_assert_common.cc.o: no symbols
callable_result.cc.o: no symbols

[symbols.txt](https://github.com/firebase/firebase-cpp-sdk/files/10450751/symbols.txt)

➜  MacOS lipo -info .../firebase-cpp-sdk-10.3.0/build/liblibuWS.a 
Architectures in the fat file: .../firebase-cpp-sdk-10.3.0/build/liblibuWS.a are: x86_64 arm64

**Comment by DellaBitta** [comment]
Hm.. I'm not sure what's going on here, then. I singled out one of this reported missing symbols `firebase::rest::Request::set_post_fields`, and I see it defined in the universal_10.15 library as `__ZN8firebase4rest7Request15set_post_fieldsEPKc`.

I have two more suggestions.

First is to add the [CMAKE_OSX_DEPLOYMENT_TARGET](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html) to the top of the cmake file. Apparently it does odd things if it's not defined before the project() clause in cmake. If you deliberately put it at the top of the cmake file then there's no question as to when its getting plumbed into cmake. I know that defining it on the command line should work, as you've done, but I'm trying to eliminate any possible errors at this point.

Additionally set the [MACOSX_DEPLOYMENT_TARGET](https://cmake.org/cmake/help/latest/envvar/MACOSX_DEPLOYMENT_TARGET.html?highlight=macosx_deployment_target) cmake flag to 10.15 s well.
