### ISSUE TITLE
Firebase feature flag support for Windows (.NET) environment

### ISSUE THREAD

**Issue by sathishkumarkaliavaradhan-okta** [firebase/firebase-cpp-sdk#1192]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: N/A
  * Firebase C++ SDK version: N/A
  * Main Firebase Components in concern: Feature flag
  * Other Firebase Components in use: Feature flag
  * Platform you are using the C++ SDK on: Windows
  * Platform you are targeting: Desktop

### [REQUIRED] Please describe the question here:

We are using the firebase feature flag service using the SDK for both Android and iOS. we also have an app in Windows environment which is developed using the .NET framework. We would like to use the firebase feature flag for the windows environment too. 
1) Do you have any plans for .NET SDK?  
2) In general how do you support the windows environment do you have SDK for windows? I see c++ SDK but it is still in beta not sure if can we use that for the production environment. 
FYI: @ncooke3 

Thanks,
Sathishkumar

**Comment by a-maurice** [comment]
1. Can you elaborate what you mean by a .NET SDK?

2. Currently we support windows (and other desktop environments) for development purposes only, and only a subset of the products are functional, which are listed at https://firebase.google.com/docs/cpp/setup?platform=ios#libraries-desktop.  But any feedback on improving desktop support is appreciated.

**Comment by sathishkumarkaliavaradhan-okta** [comment]
Thanks, @a-maurice for your reply.

1) We have developed our windows desktop client app using C# language and .NET Framework so we wanted to check if you have any firebase SDK for the .NET environment 
2) Since c++ SDK is mentioned for development purposes only, we are looking for SDK which can be integrated into the window production app. do you recommend any other SDK for the windows app production environment?
