### ISSUE TITLE
Uncaught IllegalStateException

### ISSUE THREAD

**Issue by berinhardt** [firebase/firebase-cpp-sdk#121]
### Please fill in the following fields:
Pre-built SDK from the [website](https://firebase.google.com/download/cpp) 
Firebase C++ SDK version: 6.15.1
Firebase plugins in use (Auth, Database, etc.): admob
Additional SDKs you are using (Facebook, AdMob, etc.):

- 'com.google.firebase:firebase-bom:25.8.0'
- 'com.google.ads.mediation:facebook:5.11.0.0'
- 'com.google.android.ads:mediation-test-suite:1.4.0'
- 'com.google.gms:google-services:4.3.3'

Platform you are using the C++ SDK on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

### Please describe the issue here:
There are some cases that interstitial->LoadAd(request); throws an IllegalStateException that is not caught crashing the app instead of failing the Future. I've put together a quick pr to fix it in this repo.

### Please answer the following, if applicable:
What's the issue repro rate? it almost never happens, but when it happens it always happen until you reinstall the app

**Comment by chkuang-g** [comment]
Hi @berinhardt 

Thank you for reporting this, and even better, with a pull request!

It looks like a legit fix.  However, current we cannot accept pull request on this repo until we fully migrate our build process to Github, which still needs some time.

Are you OK if we fix this from outside and publish the change in the next release?

Shawn

**Comment by berinhardt** [comment]
Of course, please do that!

**Comment by vimanyu** [comment]
Thanks for the response and the fix! We will make sure to get it in our next release. As @chkuang-g mentioned, this might take some time as we are in the middle of migrating our build process right now.

**Comment by vimanyu** [comment]
Hi @berinhardt, 
Thanks for reporting this and for the proposed fix. These changes went into the latest release. Am closing the ticket for now but please feel free to reopen if you are still noticing problems.
