### ISSUE TITLE
[Question]  Segfault on firebase::gma::Initialize

### ISSUE THREAD

**Issue by DeexCoding** [firebase/firebase-cpp-sdk#1247]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: Pre-built
  * Firebase C++ SDK version: 10.6.0
  * Main Firebase Components in concern: Google Mobile Ads (Auth, Database, etc.)
  * Other Firebase Components in use: None (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)

### [REQUIRED] Please describe the question here:

I am trying to initialize GMA, but it just throws a segfault and nothing else (project name is AndroidStudioTest, weird that the segfault leaves "an" out):

`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 23276 (Thread-6), pid 27809 (droidstudiotest)`

And there is no other error

Here is the relevant code:

`int InitGMA(struct android_app* app)
{
    JNIEnv* env = 0;
	JavaVM* jniiptr = app->activity->vm;
	jint attachResult = jniiptr->AttachCurrentThread(&env, 0);

    firebase::InitResult result;
    firebase::Future<firebase::gma::AdapterInitializationStatus> future = 
        firebase::gma::Initialize(env, app->activity->clazz, &result);`

**Comment by DeexCoding** [comment]
Call stack shows:
art_sigsegv_fault 0x00000076bc67e4b0
art::FaultManager::HandleFault(int, siginfo *, void *) 0x00000076bc67e9c4
art::SignalChain::Handler(int, siginfo *, void *) 0x000000567665aea4
<unknown> 0x0000007954307668
_JNIEnv::NewStringUTF(const char *) 0x00000076460493d8
firebase::util::FindOrLoadClassFromLoaders(_JNIEnv *, const char *) 0x00000076460493c4
firebase::util::FindClass(_JNIEnv *, const char *) 0x00000076460493c4
firebase::gma::Initialize(_JNIEnv *, _jobject *, firebase::InitResult *) 0x00000076460989dc
InitGMA(android_app *) AdsWrapper.cpp:50
...

**Comment by AlmostMatt** [comment]
Just to clarify, you are using GMA without a FirebaseApp, right?

Your sample code looks reasonable to me. I will try to reproduce and see what I can find.

**Comment by DeexCoding** [comment]
I am using it without a firebase app. I noticed if I integrate firebase (gradle plugins and everything) then it works flawlessly in the codebase, however, I would still like to use the least ammount of dependencies if possible.

**Comment by jbrettkooistra** [comment]
I am having the same issue using GMA without a FireBaseApp the details and setup are the same as the original poster except I am using a Mac. Integrating Firebase also resolves the issue for me, but I would also like to avoid this dependency. I tried updating the Firebase C++ SDK version to 10.7.0 but the issue seems to exist in that version as well. Any updates?

**Comment by AlmostMatt** [comment]
I was able to reproduce this issue. Upon looking into the code, it seems like a simple fix may be possible.

**Comment by DeexCoding** [comment]
Any updates?

**Comment by AlmostMatt** [comment]
I have now submitted a fix for this (https://github.com/firebase/firebase-cpp-sdk/pull/1320), which will be included in the next release (11.4.0)

I'm going to close this issue for now as the fix is submitted. Feel free to re-open if any issues persist after the 11.4.0 version is released.

**Comment by AlmostMatt** [comment]
The 11.4.0 release is now available, and it should include a fix for this issue.
