### ISSUE TITLE
I am getting  waring The next major release of the Firebase C++ SDK will drop support for C++11 and  my c++ version is c++ 20 standard

### ISSUE THREAD

**Issue by haris-pp** [firebase/firebase-cpp-sdk#1284]
I am using latest firbase sdk in my project and I am getting following warning 
"The next major release of the Firebase C++ SDK will " \
    "drop support for C++11, setting the new minimum C++ version to C++14."

My c++ version is  c++ 20 standard and firbase version is latest. I got build error as my compile settings treat waring as error. I am using visual studio 2022

**Comment by AlmostMatt** [comment]
I'm closing this issue, as these warnings have since been removed.
The Firebase 11.0.0 SDK has updated to use C++ 14.

There may have an issue where the warnings were shown even when not applicable, sorry for the inconvenience.
