### ISSUE TITLE
[Question] Does messaging::Subscribe create a new topic if needed ?

### ISSUE THREAD

**Issue by Neitah** [firebase/firebase-cpp-sdk#1289]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: website
  * Firebase C++ SDK version: 10.7.0
  * Main Firebase Components in concern: Messaging( Auth, Database, etc.)
  * Other Firebase Components in use: none (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)

### [REQUIRED] Please describe the question here:

I was just wondering if, when trying to subscribe to a topic that doesn't exist yet, the SDK automatically creates it. I know the kotlin method "subscribeToTopic()" does, but I couldn't find that information for the cpp sdk.

**Comment by AlmostMatt** [comment]
The Firebase C++ SDK wraps around the Android and iOS Firebase SDKs.
So on Android the C++ Subscribe internally calls the Android SDK's subscribeToTopic method. As a result, if the android SDK behaviour is to create the topic, then this should happen automatically when calling the C++ subscribe as well.
