### ISSUE TITLE
Cannot login facebook on Android 4.4.2 ( Galaxy S5 ) When updated Firebase Sdk to new version 6.2.0 ! Bad access token: {"code":190,"message":"Invalid OAuth access token."

### ISSUE THREAD

**Issue by thienphuoc** [firebase/firebase-cpp-sdk#14]
Hello Firebase SDK Team !

In my game , I used **Firebase Sdk V6.0.0** with Facebook Firebase Auth feature !
 
It works fine on all android versions ! 

Now, When I **updated Firebase C++ Sdk to new version 6.2.0** , I found a bug on Android 4.4.2 ( Galaxy S5 ) ! I think it can also occur on older version ( 4.x ) !

I also tested the new sdk version on some devices with android 8.x ,5.x.. versions ! All works fine except android 4.4.2 ( Galaxy S5 ) !

Here is the log from firebase :

**The supplied auth credential is malformed or has expired. [ Bad access token: {"code":190,"message":"Invalid OAuth access token."}**

**I/AuthChimeraService: Error description received from server: INVALID_IDP_RESPONSE : Bad access token: {"code":190,"message":"Invalid OAuth access token."}**

I think this bug from firebase sdk because I checked the facebook login status , It was successful !

I tested on some facebook accounts , but it's the same !  It does not occur this problem on android 8.1 (Vivo V9) , android 5.x (LG F460) ...!

Does this problem only occurs on older versions ? 

Eg : android 4.x 

Could Firebase SDK Team help me consider this issue ?

Thanks !

**Comment by a-maurice** [comment]
Hi @thienphuoc 

Thanks for asking about this issue.  We will look into it, and let you know what the problem is when we can.

**Comment by thienphuoc** [comment]
> Hi @thienphuoc
> 
> Thanks for asking about this issue. We will look into it, and let you know what the problem is when we can.

ok thanks you!

**Comment by cynthiajoan** [comment]
Hi @thienphuoc, sorry we didn't get back to you early. We tried a few things locally but cannot reproduce the issue. To help with your problem, can you use this [link](https://firebase.google.com/support/troubleshooter/report/bugs/) to file a firebase support issue? Please make sure your project_id and a sample Facebook token is included in the bug report cause that's critical for investigate auth problems.

Thank you very much for your patience.

**Comment by stewartmiles** [comment]
@thienphuoc since we haven't heard from you we're closing this issue.
