### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AlexOpanasevych** [firebase/firebase-cpp-sdk#1426]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: Open-Source
  * Firebase C++ SDK version: 11.4.0
  * Problematic Firebase Component: All (Auth, Database, etc.)
  * Other Firebase Components in use: All (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: Windows
  * Platform you are targeting: Desktop (iOS, Android, and/or desktop)

#### Steps to reproduce:

Followed instruction in README, created build folder, run command
```
cmake --build .
```
#### Relevant Code:

```
flatbuffers.vcxproj -> C:\Users\Sasha\Documents\projects2021\github-garbage-folder\firebase-cpp-sdk\desktop_build\ext
  ernal\src\flatbuffers-build\Debug\flatbuffers.lib
  flatc.vcxproj -> C:\Users\Sasha\Documents\projects2021\github-garbage-folder\firebase-cpp-sdk\desktop_build\external\
  src\flatbuffers-build\Debug\flatc.exe
  zlibstatic.vcxproj -> C:\Users\Sasha\Documents\projects2021\github-garbage-folder\firebase-cpp-sdk\desktop_build\exte
  rnal\src\zlib-build\Debug\zlibstaticd.lib
  Generating google_services_resource
  Traceback (most recent call last):
    File "C:\Users\Sasha\Documents\projects2021\github-garbage-folder\firebase-cpp-sdk\binary_to_array.py", line 46, in
   <module>
      from absl import app
  ModuleNotFoundError: No module named 'absl'
```

What I'm doing wrong? Btw, following Python module is installed.

**Comment by a-maurice** [comment]
Usually that error means that the absl-py module is missing.  If you have multiple versions of python installed, it could be that absl-py is installed on one, but the build is using a different python, that is missing it.  The build should be using python3, so you could always run:
`python3 -m pip install --user absl-py`
to make sure that absl-py is installed on that.
