### ISSUE TITLE
[Bug] Auth Emulator Support Doesn't Seem To Work On Windows

### ISSUE THREAD

**Issue by brianmichel** [firebase/firebase-cpp-sdk#1530]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: open source from the repo
  * Firebase C++ SDK version: ~11.3.0
  * Problematic Firebase Component: Auth (but worried about other emulators)
  * Other Firebase Components in use: Firestore, Functions
  * Platform you are using the C++ SDK on: Windows
  * Platform you are targeting: desktop

### [REQUIRED] Please describe the issue here:

I've set the environment variable `USE_AUTH_EMULATOR` in my power shell and I'm attempting to run an application that embeds the Firebase SDK into it. I see my test code correctly read out the value of `USE_AUTH_EMULATOR` from the environment so I do believe the program is picking up the correct environment values, but I don't see requests made to my local emulators, no logs are generated on the emulator side, and signing into an account that has been stored in the emulation environment also fails.

#### Steps to reproduce:

1. run `$env:USE_AUTH_EMULATOR = "true"`
2. run the application that uses the Firebase SDK

What happened? How can we make the problem occur?
The application continued to use the regularly configured Firebase environment in the cloud, and not the emulators.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

https://github.com/thebrowsercompany/firebase-cpp-sdk/blob/dece3ca27997a620098eaf1734011869228b5a44/auth/src/desktop/rpcs/auth_request.cc#L96-L116

**Comment by cynthiajoan** [comment]
@brianmichel I'd like to have two more information about your setup

1. What's the port of your auth emulator, the default one we are using is 9099, and if your emulator is starting in another port, you can use AUTH_EMULATOR_PORT variable to set it.
2.  What's. the firewall setup in your machine. Wondering if the call is blocked by the firewall.

Thanks.

**Comment by brianmichel** [comment]
> What's the port of your auth emulator, the default one we are using is 9099, and if your emulator is starting in another port, you can use AUTH_EMULATOR_PORT variable to set it.

We're using the default port of 9099, I'm just using `firebase emulators:start` to kick off the emulators which seems to use the default port you have mentioned.

> What's. the firewall setup in your machine. Wondering if the call is blocked by the firewall.

I just have a standard Windows firewall running, I can try turning it off and see what happens, if you think that's advisable. Typically Windows will prompt for network access which I believe I've granted since I see my OpenJDK instance allowed to make TCP and UDP connections
<img width="1243" alt="image" src="https://github.com/firebase/firebase-cpp-sdk/assets/63919/38368258-1e9c-487a-aec2-1867dcc7ea9a">, but let me know if there's a better way to check if the emulators have the appropriate access through the firewall.

**Comment by brianmichel** [comment]
Hey @cynthiajoan any thoughts here?

**Comment by cynthiajoan** [comment]
Hmmm, can you provide a minimum repro project, or try to use the testapp https://github.com/firebase/quickstart-cpp/tree/main/auth/testapp to repro the problem?

**Comment by brianmichel** [comment]
> Hmmm, can you provide a minimum repro project, or try to use the testapp https://github.com/firebase/quickstart-cpp/tree/main/auth/testapp to repro the problem?

I'll give the test app a try!
