### ISSUE TITLE
Including the Firebase C++ SDK in a CMake/MSVC2019 CMake project.

### ISSUE THREAD

**Issue by freekee1** [firebase/firebase-cpp-sdk#162]
* Pre-built SDK from the [website](https://firebase.google.com/download/cpp)
  * Firebase C++ SDK version: 6.16.0
  * Main Firebase Components in concern: Database
  * Other Firebase Components in use: App, Auth
  * Platform you are using the C++ SDK on: Windows
  * Platform you are targeting: desktop

### [REQUIRED] Please describe the question here:
Hi! When attempting to build a project with the prebuilt Firebase C++ SDK, using the MSVC2019 compiler and CMake on Windows, I always get the following errors. I could not seem to find out where those methods should be located, which library I might be missing/not linking.

`firebase_database.lib(f4a1508f798b6b861526e21467e4be6e_database.dir_Debug_level_db_persistence_storage_engine.obj): 
error LNK2019: unresolved external symbol "class firebase::Variant __cdecl firebase::util::FlexbufferToVariant(class flexbuffers::Reference const &)" (?FlexbufferToVariant@util@firebase@@YA?AVVariant@2@AEBVReference@flexbuffers@@@Z)
referenced in function "public: virtual class firebase::Variant __cdecl firebase::database::internal::LevelDbPersistenceStorageEngine::ServerCache(class firebase::Path const &)" (?ServerCache@LevelDbPersistenceStorageEngine@internal@database@firebase@@UEAA?AVVariant@4@AEBVPath@4@@Z)

firebase_database.lib(f4a1508f798b6b861526e21467e4be6e_database.dir_Debug_flatbuffer_conversions.obj) : error LNK2001: unresolved external symbol "class firebase::Variant __cdecl firebase::util::FlexbufferToVariant(class flexbuffers::Reference const &)" (?FlexbufferToVariant@util@firebase@@YA?AVVariant@2@AEBVReference@flexbuffers@@@Z)

firebase_database.lib(f4a1508f798b6b861526e21467e4be6e_database.dir_Debug_level_db_persistence_storage_engine.obj) : error LNK2019: unresolved external symbol "bool __cdecl firebase::util::VariantToFlexbuffer(class firebase::Variant const &,class flexbuffers::Builder *)" (?VariantToFlexbuffer@util@firebase@@YA_NAEBVVariant@2@PEAVBuilder@flexbuffers@@@Z) referenced in function "public: bool __cdecl <lambda_e4f0c2f9cb695facf4fbcf828e4775a5>::operator()(class std::vector<unsigned char,class std::allocator<unsigned char> > *)const " (??R<lambda_e4f0c2f9cb695facf4fbcf828e4775a5>@@QEBA_NPEAV?$vector@EV?$allocator@E@std@@@std@@@Z)`

Maybe anybody would kindly have a hint or any kind of help?

And a minor second question: Is clang-cl supported to build the Firebase C++ SDK itself, and/or to use the prebuilt one?

Thanks a lot in advance!

Kind regards,
Julian

**Comment by chkuang-g** [comment]
@freekee1 

Could you provide us with a sample project to reproduce this issue? Ex. Were you able to reproduce it with our [cpp-quickstart](https://github.com/firebase/quickstart-cpp)?

To answer your question about clang-cl, you should be able to build C++ SDK from source with clang-cl by following the 
 instructions on readme.md.
https://github.com/firebase/firebase-cpp-sdk

If not please report this to us so that we can take a look of it.

Shawn

**Comment by freekee1** [comment]
> @freekee1
> 
> Could you provide us with a sample project to reproduce this issue? Ex. Were you able to reproduce it with our [cpp-quickstart](https://github.com/firebase/quickstart-cpp)?
> 
> To answer your question about clang-cl, you should be able to build C++ SDK from source with clang-cl by following the
> instructions on readme.md.
> https://github.com/firebase/firebase-cpp-sdk
> 
> If not please report this to us so that we can take a look of it.
> 
> Shawn

Hi @chkuang-g, apologies for the late reply. I'm quite busy at the moment and just want to assure you I'll get back to this as soon as I can! I'll just need to find time to try the cpp-quickstart sample(s) (do they work on Windows? Its README says "iOS and Android samples") and throw stuff out of my test project for a minimal example.

As an aside: What I can report is that building (the current master) with either MSVC or clang-cl or GCC (MinGW64) currently always results in errors in the abseil library which contains invalid dllimport statements (specifically several occurrances of [C2491](https://docs.microsoft.com/en-us/troubleshoot/cpp/c2491-define-data-member-dllimport)).

Kind regards and until soon,
Julian

**Comment by vimanyu** [comment]
Hi, thanks for reporting this. We just released 6.16.1 and this should be fixed. Please let us know if you are still running into this.

**Comment by remaininlight** [comment]
I am using the new release 6.16.1 and running into this same issue when I attempt to link with -lfirebase_database on macOS for desktop:

Error:Undefined symbol 'firebase::util::VariantToFlexbuffer(firebase::Variant const&, flexbuffers::Builder*)'
Referenced from:
bool firebase::database::internal::CallOnEachLeaf<firebase::database::internal::PrepareBatchOverwrite(firebase::Path const&, firebase::Variant const&, firebase::database::internal::BufferedWriteBatch*)::$_9>(firebase::Path const&, firebase::Variant const&, firebase::database::internal::PrepareBatchOverwrite(firebase::Path const&, firebase::Variant const&, firebase::database::internal::BufferedWriteBatch*)::$_9 const&) in libfirebase_database.a(f07225c2ba0bc10039fd88577855db1c_level_db_persistence_storage_engine.o)

Any advice/ work arounds gratefully received

**Comment by vimanyu** [comment]
@remaininlight  Could you please provide some info on how you are building your project? What cmake options are you passing? Are you linking against our prebuilt libraries or are you building the libraries yourself from scratch from our open source SDK?

Also, are you seeing this issue in the database quickstart example?

**Comment by nconcepts** [comment]
Hi,
Same issue here.
I'm building on QT under Mac OSX, target Desketop.
I just linked with the pre-build libraries darwin/x86_64
If I just create the App it's ok, as soon as I get the db instance I get the same error

My cpp:
`    AppOptions options;
    options.set_database_url("https://xxxx.firebaseio.com");
    App *app = App::Create(options);

    database::Database *db = database::Database::GetInstance(app);`

My .Pro file
`macx: LIBS += -L$$PWD/firebase_cpp_sdk/libs/darwin/x86_64/ -lfirebase_app -lfirebase_database -lfirebase_admob -lfirebase_analytics -lfirebase_auth -lfirebase_dynamic_links -lfirebase_firestore -lfirebase_functions -lfirebase_instance_id -lfirebase_messaging -lfirebase_remote_config -lfirebase_storage

INCLUDEPATH += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64
DEPENDPATH += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64

macx: PRE_TARGETDEPS += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64/libfirebase_admob.a
macx: PRE_TARGETDEPS += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64/libfirebase_analytics.a
macx: PRE_TARGETDEPS += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64/libfirebase_app.a
macx: PRE_TARGETDEPS += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64/libfirebase_auth.a
macx: PRE_TARGETDEPS += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64/libfirebase_database.a
macx: PRE_TARGETDEPS += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64/libfirebase_dynamic_links.a
macx: PRE_TARGETDEPS += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64/libfirebase_firestore.a
macx: PRE_TARGETDEPS += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64/libfirebase_functions.a
macx: PRE_TARGETDEPS += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64/libfirebase_instance_id.a
macx: PRE_TARGETDEPS += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64/libfirebase_messaging.a
macx: PRE_TARGETDEPS += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64/libfirebase_remote_config.a
macx: PRE_TARGETDEPS += $$PWD/firebase_cpp_sdk/libs/darwin/x86_64/libfirebase_storage.a`

My error
`Undefined symbols for architecture x86_64:
  "firebase::util::VariantToFlexbuffer(firebase::Variant const&, flexbuffers::Builder*)", referenced from:
      bool firebase::database::internal::CallOnEachLeaf<firebase::database::internal::PrepareBatchOverwrite(firebase::Path const&, firebase::Variant const&, firebase::database::internal::BufferedWriteBatch*)::$_9>(firebase::Path const&, firebase::Variant const&, firebase::database::internal::PrepareBatchOverwrite(firebase::Path const&, firebase::Variant const&, firebase::database::internal::BufferedWriteBatch*)::$_9 const&) in libfirebase_database.a(f07225c2ba0bc10039fd88577855db1c_level_db_persistence_storage_engine.o)
ld: symbol(s) not found for architecture x86_64`

**Comment by TricksterGit** [comment]
Hi,
I have exactly the same issue when building it on Windows with VS2017 (environment msvc_x64_x86). I am using version 6.16.1.

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\firebase_database.lib(3a24efa24aa752e49ffc1576757b342b_database.dir_Debug_level_db_persistence_storage_engine.obj) : error LNK2019: unresolved external symbol "bool __cdecl firebase::util::VariantToFlexbuffer(class firebase::Variant const &,class flexbuffers::Builder *)" (?VariantToFlexbuffer@util@firebase@@YA_NAEBVVariant@2@PEAVBuilder@flexbuffers@@@Z) referenced in function "public: bool __cdecl <lambda_e4f0c2f9cb695facf4fbcf828e4775a5>::operator()(class std::vector<unsigned char,class std::allocator<unsigned char> > *)const " (??R<lambda_e4f0c2f9cb695facf4fbcf828e4775a5>@@QEBA_NPEAV?$vector@EV?$allocator@E@std@@@std@@@Z)
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ResultsHandlerLib\ResultsHandlerLib.dll : fatal error LNK1120: 1 unresolved externals
```
