### ISSUE TITLE
"ITMS-90426: Invalid Swift Support"

### ISSUE THREAD

**Issue by shokarta** [firebase/firebase-cpp-sdk#1666]
### Description

as use only c++ and cmake, including firebase ios sdk requires to also include Swift language support into cmake.
which I did, and I can build and deploy the app just fine.

However when uploading generaed app to TestFlight / AppStore it gives me following error:
![image](https://github.com/user-attachments/assets/2282d036-4aa7-49cb-b96c-199d6598eaf2)

when I open generated *.app to check, it realy does not contain SwiftSupport folder.
So I guess I need to tell Cmake to require generating this folder upon build?
cmakes generate xproject which I open in xcode to build...
In the documentations neither examples I found anything how can I influence this from Cmake, neither directly set in xcode.

same/similar question unaswered here https://github.com/firebase/firebase-ios-sdk/issues/10006

### Firebase SDK Version

11.3

### Xcode Version

16.0.1

### Installation Method

N/A

### Firebase Product(s)

Analytics, Messaging

### Targeted Platforms

iOS

**Comment by paulb777** [comment]
Transferred to the firebase-cpp-sdk repo to investigate how to apply the guidance from https://github.com/firebase/firebase-ios-sdk/issues/10006 to C++ and cmake.

**Comment by shokarta** [comment]
@paulb777 have you created issue for firebase-cpp-sdk? can i please have a link?

**Comment by paulb777** [comment]
https://github.com/firebase/firebase-cpp-sdk/issues/1666

**Comment by shokarta** [comment]
thank you, however i still think its pure ios sdk issue, as this happens only when to c++ project load swift stuff... which happens only in firebase ios sdk :)

**Comment by paulb777** [comment]
The solution for the pure iOS issue is described in https://github.com/firebase/firebase-ios-sdk/issues/10006. it sounds like you need additional help for a C++ context.

**Comment by shokarta** [comment]
I dont see any solution there... theoretical solution was to include swift file which I already did with no success, and this was also mentioned by @ndahlquist that he did and didnt help. "contains embedded Swift" also can say didnt help me neither for that topic. No other solution was proposed there yet
