### ISSUE TITLE
Crashing on firebase::app::Create

### ISSUE THREAD

**Issue by VGolets** [firebase/firebase-cpp-sdk#167]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11
  * Firebase C++ SDK version: v6.12.0
  * Firebase IOS SDK version: v6.33.0
  * Firebase Component: Firebase Crashlytics (Firebase Analytics)
  * Installation method: Zip file

### [REQUIRED] Step 2: Describe the problem

Сrash on start with container-overflow in Firebase C ++ wrapper.

#### Steps to reproduce:

```
==546==ERROR: AddressSanitizer: container-overflow on address 0x000118109a40 at pc 0x0001122191d8 bp 0x00016ae39030 sp 0x00016ae387c0
WRITE of size 159 at 0x000118109a40 thread T0
    #0 0x1122191d4 in wrap_memmove
    firebase/firebase-ios-sdk#1 0x106e85788 in std::__1::vector<char, std::__1::allocator<char> >::vector<char const*>(char const*, std::__1::enable_if<(__is_forward_iterator<char const*>::value) && (is_constructible<char, std::__1::iterator_traits<char const*>::reference>::value), char const*>::type)
    firebase/firebase-ios-sdk#2 0x106e851c4 in firebase::app_common::RegisterLibrariesFromUserAgent(char const*)
    firebase/firebase-ios-sdk#3 0x106e868f8 in firebase::App::RegisterLibrary(char const*, char const*) 
    firebase/firebase-ios-sdk#4 0x106e84840 in firebase::app_common::AddApp(firebase::App*, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, firebase::InitResult, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, firebase::InitResult> > >*)
    firebase/firebase-ios-sdk#5 0x106e86714 in firebase::App::Create(firebase::AppOptions const&, char const*) 
    firebase/firebase-ios-sdk#6 0x106e85f04 in firebase::App::Create() 
    firebase/firebase-ios-sdk#7 0x10569349c in -[GameDelegate application:didFinishLaunchingWithOptions:] 
```

**Comment by paulb777** [comment]
Rerouted to Firebase C++ Issue list since the backtrace is all C++.

**Comment by vimanyu** [comment]
Hi @VGolets,
I couldn't reproduce this issue locally on my machine. I built the [analytics quickstart example](https://github.com/firebase/quickstart-cpp) with the following settings,

- Built directly pointing to the latest firebase source SDK
```
cmake -G Xcode -S . -B build -DFIREBASE_CPP_SDK_DIR=~/firebase/firebase-cpp-sdk -DOPENSSL_ROOT_DIR=~/homebrew/Cellar/openssl\@1.1/1.1.1g

cmake --build build -j8

Copy a google-services.json file into the executable directory
./build/Debug/desktop_testapp
```

- Built with prebuilt firebase libraries 6.11.0
```
cmake -G Xcode -S . -B build_prebuilt_6.11.0 -DFIREBASE_CPP_SDK_DIR=~/firebase/prebuilt/firebase-cpp-sdk
cmake --build build_prebuilt_6.11.0
```

- Built with prebuilt firebase libraries 6.15.1
```
cmake -G Xcode -S . -B build_prebuilt_6.15.1 -DFIREBASE_CPP_SDK_DIR=~/firebase/prebuilt/firebase-cpp-sdk
cmake --build build_prebuilt_6.15.1
```

All of the cases above worked as expected.
Could you please try running the quickstart example and let us know if its not working? It will be great to reproduce this bug locally.

**Comment by vimanyu** [comment]
Another thing that might not work is the combination of C++ SDK and iOS SDK here.
The iOS SDK that is being used (v6.33.0) is too recent.

Our prebuilt libraries were built and tested with following iOS SDK versions,
FIrebase C++ SDK -> Firebase iOS SDK
6.16.0 -> 6.32.2
6.12.0 -> 6.16.0
