### ISSUE TITLE
Fix deprecated methods activateFetched, setConfigSettings

### ISSUE THREAD

**Issue by crazyhappygame** [firebase/firebase-cpp-sdk#17]
According to 
https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/FirebaseRemoteConfig.html#public-void-setconfigsettings-firebaseremoteconfigsettings-settings
C++ SDK uses deprecated methods activateFetched, setConfigSettings

**Comment by chkuang-g** [comment]
Thank you for reporting this.

I think you should still be able to use it with no problem.  But we will change it.

**Comment by crazyhappygame** [comment]
Yes it works but I have a filling that "Async" versions provide better user experience ;)
