### ISSUE TITLE
AdMob variable g_java_vm initialized to late on Android when Initialize is done without firebase.

### ISSUE THREAD

**Issue by SimonSuckut** [firebase/firebase-cpp-sdk#192]
* Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: prebuild
  * Firebase C++ SDK version: 6.16.1
  * Problematic Firebase Component: AdMob
  * Other Firebase Components in use: None
  * Platform you are using the C++ SDK on: Linux (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)

Hello, 
I came across an issue in the admob c++ sdk when trying to initialize it without firebase. The variable g_java_vm in admob_android.cc is initialized in line 195, but used in line 187 by the called function admob::RegisterNatives, which calls GetJNI. Initializing the variable earlier would solve the problem. This only happens when ads are initialized without firebase.

#### Relevant Code:

```
JNIEnv* GetJNI() {
  if (g_app) {
    return g_app->GetJNIEnv();
  } else {
    FIREBASE_ASSERT(g_java_vm); //This assertion fails
    return firebase::util::GetThreadsafeJNIEnv(g_java_vm);
  }
}

**Comment by chkuang-g** [comment]
Hi @SimonSuckut 

I think what you need is to move [this line](https://github.com/firebase/firebase-cpp-sdk/blob/f0a9d5b65e3a014aee347ea9bb3b664cdce2ae55/admob/src/android/admob_android.cc#L195) to be above `admob::RegisterNatives()` call.

However, I am not sure if this is a valid use-case to initialize Admob without initializing Firebase App. And this use-case is definitely tested through our [integration test](https://github.com/firebase/quickstart-cpp/blob/master/admob/testapp/src/common_main.cc#L138). 

Is there a particular reason you need to do so?

Shawn

**Comment by jonsimantov** [comment]
We've got a fix on deck for the next release. Thanks for the heads up!
