### ISSUE TITLE
firestore support

### ISSUE THREAD

**Issue by alexodus** [firebase/firebase-cpp-sdk#2]
when will there be support for Firestore?

**Comment by wilhuff** [comment]
We can't publicly promise timelines, so I can't say when this will happen. We are working on this and for the Firestore SDK team, it's our highest priority.

If you're interested in following development, it's mostly happening over at https://github.com/firebase/firebase-ios-sdk/tree/master/Firestore.

**Comment by JakeStoeffler** [comment]
@wilhuff Any update on how this is progressing? I can see the commits in the repo you linked, but it's hard for me to tell how much work is remaining. Also, can you comment on which platforms will be supported by the C++ Firestore SDK? Will it be accessible from Android, iOS, and desktop?

**Comment by wilhuff** [comment]
Initially Firestore C++ will support iOS and Android. Desktop workflow support will come later but not by much. Firebase generally supports desktop platforms as a means of supporting mobile development though: https://firebase.google.com/docs/unity/setup#desktop_workflow.

**Comment by JakeStoeffler** [comment]
Thanks @wilhuff, do you think desktop will eventually be supported for real? I have an embedded Linux device I would love to be able to use Firebase on :)

**Comment by wilhuff** [comment]
For hobbyist use, do what you like :-). The issue is more about which environments we can commercially support and in some cases about choosing which use cases we optimize for.

As far as work left goes and easy way to estimate is to look at source files under https://github.com/firebase/firebase-ios-sdk/tree/master/Firestore/Source. Everything not in `API` has to be migrated. Many of these classes are in a state of partial migration already.

**Comment by JakeStoeffler** [comment]
Sure, I understand that you can't support everyone. I would be looking to
use the C++ SDK for Firestore on a publicly released Linux device. Is
supporting such a use case part of the current plan? I suspect it is
unlikely to happen anytime soon, just wondering if you could confirm my
suspicion.

**Comment by wilhuff** [comment]
There's a difference between platforms that we support and those where the product can be made to function.

Supporting a platform means we're going to document exactly how to use it there, qualify releases for it, produce quickstarts for it, etc. We're also going to spend engineering resources to ensure that we're getting the most out of the platform. If you need help, you'll be able to contact Firebase support about it.

On secondary platforms, you're going to be much more on your own. Firebase support won't be able to help you. You may need to contribute portability fixes, cross-compilation fixes, or specific support for platform features of your device. 

So bottom line: will Firestore work on LInux? Absolutely. One of my team members uses it as their primary development platform. He holds me to account whenever I write code that clang accepts but gcc doesn't. We specifically undertook building the C++ SDK the way we have to make your use case possible.

Will this be fully supported to the degree we support iOS and Android? That's not likely, at least not for a while. Whether or not this is an acceptable state of affairs for you depends a lot on your comfort level with contributing to making it work for you.

I suggest giving what we have a spin: https://github.com/firebase/firebase-ios-sdk/blob/master/CMAKE.md. This isn't a complete SDK yet, but If it builds and tests pass it's likely this will work out.

**Comment by SebastienDevQuebec** [comment]
Hi wilhuff,

"We can't publicly promise timelines" Did that change ? are you able to give an approximation now? i bet you guys are almost done.

looking forward for an update, Thanks.

**Comment by wilhuff** [comment]
"We can't publicly promise timelines" is a policy position. You should make decisions for your project/business based on what's currently available, not the promise of what's coming. By not publicly committing to date we can't break any implicit contract that might be implied.

So I still can't give any approximation, but yes, we've made good progress.

**Comment by wilhuff** [comment]
I should have commented here earlier, but last month we released [Firebase C++ SDK 6.12.0](https://firebase.google.com/support/release-notes/cpp-relnotes#version_6120_-_march_5_2020) which includes an alpha release of Firestore. This release is _experimental_:

  * We expect there will be breaking changes to the API
  * Some features are missing (for example: IN queries)
  * You may uncover issues for which we can't supply an immediate resolution

Please try it out and let us know how it goes. Read more about how to get this release in [Add Firebase to your C++ project](https://firebase.google.com/docs/cpp/setup).

We're very excited to (finally) get this in your hands and hear how it works for you!

**Comment by heliam1** [comment]
Does this mean it's hypothetically possible to use Firestore C++ SDK on a Windows application now?

**Comment by wilhuff** [comment]
The general Firebase policy for platform support has not changed. Yes, you can build on Windows, but the intent behind what we’re doing is to optimize build and test cycles for mobile game development while working on desktop. We’re not currently targeting complete support for desktop environments though you may find what we have could be sufficient for your needs.

Note that Firebase-wide desktop developer workflow support is still in beta and the Firestone C++ API is still in alpha.
