### ISSUE TITLE
Add iOS CMake support

### ISSUE THREAD

**Issue by crazyhappygame** [firebase/firebase-cpp-sdk#20]
In CMake https://github.com/firebase/firebase-cpp-sdk/blob/master/release_build_files/CMakeLists.txt#L31 there is only :
```
elseif(APPLE)
    set(FIREBASE_SDK_LIBDIR ${FIREBASE_CPP_SDK_DIR}/libs/darwin/universal))
```
Please add also ios branch

**Comment by crazyhappygame** [comment]
FYI. Starting from cmake 14.0 there is native support for iOS:
https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos

Some game engines like cocos2d-x https://github.com/cocos2d/cocos2d-x switched to cmake

**Comment by stewartmiles** [comment]
We've supported this since we first open sourced the project.  See https://github.com/firebase/firebase-cpp-sdk#building-with-cmake-for-ios

**Comment by crazyhappygame** [comment]
This ticket is not about building but about using in iOS cmake project

**Comment by crazyhappygame** [comment]
@stewartmiles please reopen this issue

**Comment by stewartmiles** [comment]
@crazyhappygame it looks like you opened the feature request https://github.com/firebase/firebase-cpp-sdk/issues/22 feel free to follow up on there.

**Comment by crazyhappygame** [comment]
@stewartmiles there are 2 things:
1. Building firebase-cpp-sdk with CMake 
2. Using firebase-cpp-sdk in CMake project

There are both about CMake but those are completely different use cases....
