### ISSUE TITLE
[Question] arm64 Apple support (Apple Silicon)

### ISSUE THREAD

**Issue by mtytel** [firebase/firebase-cpp-sdk#206]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: _____
  * Firebase C++ SDK version: 6.16.0
  * Main Firebase Components in concern: Auth
  * Other Firebase Components in use: None
  * Platform you are using the C++ SDK on: Mac
  * Platform you are targeting: Mac

### [REQUIRED] Please describe the question here:
I'm porting my app to the newer ARM macs and I had thought the universal builds were for arm64 but it looks like they are 32/64 bit universal instead. Is there anyway to get built frameworks for mac arm64 architecture? Or does anyone know if I try and build from source will it work?

Thanks!

**Comment by DellaBitta** [comment]
I've added this as a feature request. Internal ticket b/175209675.

We'll work to provide precompiled versions for working on the new Arm Macs, and a framework for running simulators on Arm Macs.  For now you could compile for macs from source by doing a build from this repo with '-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64' defined.  I hope this helps!

**Comment by mtytel** [comment]
Ah great, thanks for the pointers.
I'm not the greatest at cmake so am running into some unrelated config/build issues but I'll let you know if it works when I get it compiling.

**Comment by mtytel** [comment]
I can't seem to figure out how to create the frameworks correctly. I've created the xcode project with this command but after linking I get asserts in the AddCompletionCallback of ReferenceCountedFutureImpl:

cmake -DFIREBASE_XCODE_TARGET_FORMAT=frameworks -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl "-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64" -G "Xcode" -T buildsystem=1 ../firebase-cpp-sdk

I don't think this is an ARM specific issue and is just the way I created the frameworks because it doesn't work when building the x86_64 target either.

It doesn't look like there are any code changes necessary to build universal arm64;x86_64 builds so is it possible to get this put into the next build cycle?

**Comment by DellaBitta** [comment]
Hi @mtytel,

We recently started looking into this ourselves and it wasn't as straightforward as we had hoped. Unfortunately I don't have much guidance to offer you, and we can't yet commit to which release milestone will have arm64 build support.  We're working on it though!

**Comment by mtytel** [comment]
Ah dang.
Thanks for the update!

**Comment by mtytel** [comment]
Is there any update on mac arm support? I saw some changes for mac arm64 cmake builds but not sure if that was related.

**Comment by mtytel** [comment]
Hey just want to check in on this one again. Any closer on building an arm64/x86_64 universal build?

**Comment by DellaBitta** [comment]
Hi @mtytel,

We cannot publicly commit to any timelines, but this is indeed still on our roadmap.

**Comment by jonsimantov** [comment]
Hello!

M1 (ARM) Mac support has been added as of [version 8.6.0](https://github.com/firebase/firebase-cpp-sdk/releases/tag/v8.6.0). The universal frameworks in frameworks/darwin/universal now include arm64 slices.

(Please note that the minimum Xcode version has been updated to 12.2 in order to support ARM.)
