### ISSUE TITLE
Executing cloud function always results in kErrorInternal returned by future

### ISSUE THREAD

**Issue by waj334** [firebase/firebase-cpp-sdk#221]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: prebuilt
  * Firebase C++ SDK version: 6.16.1
  * Problematic Firebase Component: Functions
  * Other Firebase Components in use: Auth
  * Platform you are using the C++ SDK on: Windows
  * Platform you are targeting: desktop

### [REQUIRED] Please describe the issue here:

The future returned by firebase::functions::HttpsCallableReference::Call(const firebase::Variant &data) always returns with error set to kErrorInternal even when the cloud function responds with http status code 200.

#### Steps to reproduce:

1. Create Golang 1.13 cloud function
2. Call using C++ API
3. Check if Future::error() is not kErrorNone

#### Log
```
Function execution took 273 ms, finished with status code: 200
```

#### Relevant Code:

```
firebase::functions::Functions* functions
    = firebase::functions::Functions::GetInstance(firebase::App::GetInstance());
auto func= functions->GetHttpsCallable("MyFunc");
auto params = firebase::Variant::EmptyMap();
    //set params....

auto future = func.Call(params);

future.OnCompletion([this](const auto& future) {
    if (future.error() != firebase::functions::kErrorNone) { //<------------ this is never false
      QMetaObject::invokeMethod(this, [this, future]() {
        QMessageBox::critical(this, "Error", future.error_message());
      }, Qt::QueuedConnection);
    }
  });
```

**Comment by alexames** [comment]
What error code are you getting from `future.error()`? A status code of 200 should map to `kErrorNone` which suggests that you shouldn't be getting an error so that's odd.

Do you get this issue when you run the [C++ quickstart testapp?](https://github.com/firebase/quickstart-cpp/)
