### ISSUE TITLE
Firestore linking is not available for Windows (Desktop)

### ISSUE THREAD

**Issue by MasterCna** [firebase/firebase-cpp-sdk#227]
I just wanted to use Firestore with a quick and small example like:
`Firestore* db = Firestore::GetInstance();`

but after linking with `Firestore-core.lib` and `Firebase-firestore-d.lib` gives me bunch of error containing:
`error LNK2019: unresolved external symbol "public: void __cdecl firebase::firestore::api::WriteBatch::SetData` etc.
I linked all dependencies but after that error is:
`firebase_firestore-d.lib(write_batch_ios.obj) `, the **iOS** extension is added to all linking errors.

Does really Firestore support Windows for Firestore stuff?

**Comment by alexames** [comment]
Hi @MasterCna, can you give me a little more information? What build system are you using and how are you linking Firestore? Which version of Firestore are you using?
