### ISSUE TITLE
Tag for version 6.6.1 release

### ISSUE THREAD

**Issue by frankosterfeld** [firebase/firebase-cpp-sdk#26]
When I follow the download link on https://firebase.google.com/download/cpp, I get firebase_cpp_sdk_6.6.1.zip, but I don't see a tag for it. Am I'm missing something, is the zip wrongly named, or did someone forget to push the tag?

**Comment by a-maurice** [comment]
Hi @frankosterfeld 

Sorry for the delay in response.  There was a problem that was affecting the closed source build that 6.6.1 was fixing, which doesn't come up in the open source build (the build process is slightly different, as the dependencies are baked into the closed source libraries to make them easier to use).  Hence why the GitHub repo is missing a 6.6.1 release label.  We'll look into making this a bit clearer in the future, as it is a bit odd.

Hopefully that helps clarify things!
