### ISSUE TITLE
Prebuilt 7.0.1 frameworks and libraries for iOS missing bitcode

### ISSUE THREAD

**Issue by Olof-IL** [firebase/firebase-cpp-sdk#266]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: Pre-built SDK
  * Firebase C++ SDK version: 7.0.1
  * Problematic Firebase Component: App,Auth,Firestore,Analytics,Messaging,Storage (probably all of them)
  * Other Firebase Components in use: Same as above
  * Platform you are using the C++ SDK on: Mac
  * Platform you are targeting: iOS

### [REQUIRED] Please describe the issue here:

Libraries missing BITCODE support. I get this error from ld for both the static library and framework versions:

    ld: '../Dependencies/firebase_cpp/libs/ios/universal/libfirebase_app.a(util_ios.mm.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '../Dependencies/firebase_cpp/libs/ios/universal/libfirebase_app.a' for architecture arm64

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
#### Steps to reproduce:

Just try to build using the latest prebuilt SDK.

Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ?

YES!

What's the issue repro rate? (eg 100%, 1/5 etc).

100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Updated Pods to 7.0.0 
Also increased platform to 11.0 since it refused to download pods with too low platform version.
Replaced firebase_cpp_sdk with latest Prebuilt 7.0.1 
Try build with XCode (I used the firestore test-app since I had it up and running since before)

Result:
    
    ld: '../../firebase_cpp_sdk/frameworks/ios/arm64/firebase.framework/firebase(util_ios.mm.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '../../firebase_cpp_sdk/frameworks/ios/arm64/firebase.framework/firebase'

#### Relevant Code:

No code change from quickstart app, except minor build fixes. Attaching patch with all my changes from master branch of quickstart app

[patch.txt](https://github.com/firebase/firebase-cpp-sdk/files/5918861/patch.txt)

**Comment by Olof-IL** [comment]
As a workaround I've disabled bitcode for my target for now. Not sure how much of an issue this is, bitcode still seems to be optional for iOS, but the last version (6.16.1) didn't have any issues with bitcode support.

I also noticed right now that the remote_config libraries seem to have bitcode enabled in 7.0.1, just thought I should mention that.

**Comment by patm1987** [comment]
Hi @Olof-IL ,

It looks like this might have been a misconfiguration in when building the latest SDK, and it's intended that bitcode should work. I'll mark this as a bug, but if this is a blocker for you now (ie: you're building for tvOS or watchOS), you might have luck building from the source on this repo.

**Comment by jonsimantov** [comment]
Thanks for letting us know about this issue. A fix (#276) has been merged into our development branch and will be included in the next binary SDK release.
