### ISSUE TITLE
Link issue on iOS with Firebase C++ SDK version 7.1.0

### ISSUE THREAD

**Issue by moleki** [firebase/firebase-cpp-sdk#302]
### [REQUIRED] Please fill in the following fields:

  * Firebase C++ SDK version: 7.1.0
  * Problematic Firebase Component: RemoteConfig
  * Other Firebase Components in use: Analytics
  * Platform you are using the C++ SDK on: Mac
  * Platform you are targeting: iOS

Hey, we just tried to upgrade to firebase c++ sdk 7.1.0 but this time it fails to link on iOS

```
Undefined symbols for architecture arm64:
  "firebase::AppDataDir(char const*, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)", referenced from:
      firebase::(anonymous namespace)::GetFilename(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in firebase(heartbeat_date_storage_desktop.cc.o)
ld: symbol(s) not found for architecture arm64
```

We are only using the following frameworks :
 - firebase.framework
- firebase_remote_config.framework
- firebase_analytics.framework

**Comment by chkuang-g** [comment]
I think there is a missing line in Cmake. 

Before we release a patch for this, this is what you need to do.

1. Go to [this line](https://github.com/firebase/firebase-cpp-sdk/blob/0cf2f97d1a86b9cb0d3d01f85a954b83773438be/app/CMakeLists.txt#L169)
2. Add `src/filesystem_apple.mm` in the end.  It should look like
   ```
   set(app_ios_SRCS
       src/app_ios.mm
       src/util_ios.mm
       src/heartbeat_date_storage_desktop.cc
       src/heartbeat_info_desktop.cc
       src/invites/ios/invites_receiver_internal_ios.mm
       src/invites/ios/invites_ios_startup.mm
       src/uuid_ios_darwin.mm
       src/filesystem_apple.mm)
   ```
This should fix the link issue.

Let us know if this works for you.

**Comment by moleki** [comment]
We download the firebase cpp sdk directly from this [page](https://firebase.google.com/download/cpp).
The framework are already built. Also we tried again with the latest 7.1.1 and we have the same issue.

I tried downloading the source code and modifying the CMakeLists.txt as suggested but the compilation fails
$ cmake --build . --target firebase_analytics
[  4%] Built target firebase_flatc_prebuild
Scanning dependencies of target firebase_app
[  4%] Building CXX object app/CMakeFiles/firebase_app.dir/src/log_ios.mm.o
/Users/molekimoleki/Downloads/firebase-cpp-sdk-main/app/src/log_ios.mm:21:9: fatal error: 'FIRConfiguration.h' file not found
#import "FIRConfiguration.h"
        ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [app/CMakeFiles/firebase_app.dir/src/log_ios.mm.o] Error 1
make[2]: *** [app/CMakeFiles/firebase_app.dir/all] Error 2
make[1]: *** [analytics/CMakeFiles/firebase_analytics.dir/rule] Error 2


Best would be to release a patch directly. Why are we the only one seeing this issue?

**Comment by moleki** [comment]
Ok, I managed to compile and link and everything seems to be working fine. I had to update the pods in ios_pods. 
It is now working after linking with firebase_app. Interestingly `firebase_app` doesn't exist in the version already precompiled [from this page](https://firebase.google.com/download/cpp), it is `firebase`

**Comment by cynthiajoan** [comment]
Hi @moleki, glad to see your problem is solved, so I will close this issue for now. If you have any further related questions, please feel free to reopen it.
