### ISSUE TITLE
Ambiguous component name in struct remote_config::ConfigSettings

### ISSUE THREAD

**Issue by stephenhurry** [firebase/firebase-cpp-sdk#305]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: website
  * Firebase C++ SDK version: 7.1.1
  * Problematic Firebase Component: Remote Config
  * Other Firebase Components in use: Auth, Database, Analytics, Crashlytics
  * Platform you are using the C++ SDK on: Mac)
  * Platform you are targeting: iOS, Android

#### Relevant Code:

```c++
/// @brief Configurations for Remote Config behavior.
struct ConfigSettings {
  /// The timeout specifies how long the client should wait for a connection to
  /// the Firebase Remote Config servers.
  ///
  /// @note A fetch call will fail if it takes longer than the specified timeout
  /// to connect to the Remote Config servers. Default is 60 seconds.
  uint64_t fetch_timeout_in_milliseconds = kDefaultTimeoutInMilliseconds;

  /// The minimum interval between successive fetch calls.
  ///
  /// @note Fetches less than duration seconds after the last fetch from the
  /// Firebase Remote Config server would use values returned during the last
  /// fetch. Default is 12 hours.
  uint64_t minimum_fetch_interval_in_milliseconds = kDefaultCacheExpiration;
};
```
`minimum_fetch_interval_in_milliseconds` should be renamed to `minimum_fetch_interval_in_seconds` as stated in the definition of `kDefaultCacheExpiration`.

And please tell me the appropriate order to call these methods: `EnsureInitialized`, `SetConfigSettings`, `SetDefaults`, `FetchAndActivate` on the `RemoteConfig` instance. I cannot change the fetch interval through `SetConfigSettings`.

**Comment by vimanyu** [comment]
Hi @stephenhurry,
Thanks for bringing this up. Have filed a bug for this.
For the order, the following should work,
1. EnsureInitialzed
2. SetConfigSettings or SetDefaults (order doesn't matter for these 2)
3. FetchAndActivate

**Comment by vimanyu** [comment]
PR is created for this and will go out in the next release.
https://github.com/firebase/firebase-cpp-sdk/pull/311
