### ISSUE TITLE
Getting unqualified-id when using standalone includes

### ISSUE THREAD

**Issue by levongh** [firebase/firebase-cpp-sdk#33]
### Please fill in the following fields:
Firebase C++ SDK version: 6.7.0
Firebase plugins in use (Auth, Database, etc.): app
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the C++ SDK on (Mac, Windows, or Linux): Linux
Platform you are targeting (iOS, Android, and/or desktop): decktop

### Please describe the issue here:
added include to project
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/firebase/)

Here is the code to reproduce 
#include "firebase/app.h"

int main()
{

return 0;
}

firebase/firebase/variant.h:357:18: error: expected unqualified-id before numeric constant
   static Variant False() { return Variant::FromBool(false); }
                  ^
firebase/firebase/variant.h:362:18: error: expected unqualified-id before numeric constant
   static Variant True() { return Variant::FromBool(true); }

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc) 5

**Comment by chkuang-g** [comment]
Hi @levongh 

After googling the error message, it seems to relate to macro (ex. "#define") or incorrectly express a numeric number (ex. "1,000" instead of "1000")

Is it possible that some other source code you included in your project which is causing this?

Shawn
