### ISSUE TITLE
undefined reference to `firebase::g_storage_initializer'

### ISSUE THREAD

**Issue by levongh** [firebase/firebase-cpp-sdk#34]
### Please fill in the following fields:
Firebase C++ SDK version: 6.7.0
Firebase plugins in use (Auth, Database, etc.):Storage
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the C++ SDK on (Mac, Windows, or Linux): Linux
Platform you are targeting (iOS, Android, and/or desktop): decktop

### Please describe the issue here:
after adding storage.h include getting linking error, but I am linking all libs to executable.
here is the code to reproduce the issue.
#include "firebase/storage.h"

int main()
{
   return 0;
}

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ?

What's the issue repro rate? (eg 100%, 1/5 etc)

**Comment by a-maurice** [comment]
Hi @levongh 

I haven't had any luck reproducing this problem.  Are you using CMake to link in the library?  If you could, can you share your CMakeLists file?  Otherwise, are you using any additional linker flags, or other settings?

**Comment by levongh** [comment]
Hi @a-maurice, 

I have used  library Prebuilt version. Unfortunately I can not share my CMakeLists.txt.
But firebase part is the following
`include_directories(${CMAKE_CURRENT_SOURCE_DIR}/firebase-cpp-sdk/include`
link_directories( ${CMAKE_CURRENT_SOURCE_DIR}/firebase-cpp-sdk/libs/linux/x86_64/)

**Comment by a-maurice** [comment]
Ah, so `link_directories` just tells it what directories it should look in when told to link in a library, not which libraries to link.

Instead of those two lines, the prebuilt version ships with a CMake list file to simplify including it, which you can use via:
```
add_subdirectory(firebase-cpp-sdk)
target_link_libraries(<YOUR_TARGET_HERE> firebase_storage)
```

You can see this behavior in the C++ quickstart, here: https://github.com/firebase/quickstart-cpp/blob/master/storage/testapp/CMakeLists.txt

**Comment by levongh** [comment]
Thank you. It fixed my issue.
