### ISSUE TITLE
Compiler Error in CMake project

### ISSUE THREAD

**Issue by k2ncore** [firebase/firebase-cpp-sdk#36]
Hello I am trying to compile my project with Firebase SDK integrated.

but getting these errors

error: no template named 'function' in namespace 'std' at the following code sections 

this is from future_impl.h

`#if defined(FIREBASE_USE_STD_FUNCTION)
  /// Register a callback that will be called when this future's status is set
  /// to Complete.
  ///
  /// If `clear_existing_callbacks` is true, then the new callback
  /// will replace any existing callbacks, otherwise it will be added to the
  /// list of callbacks.
  ///
  /// The future's result data will be passed back when the callback is
  /// called.
  ///
  /// @return A handle that can be passed to `FutureBase::RemoveCompletion`.
  virtual CompletionCallbackHandle AddCompletionCallbackLambda(
      FutureHandle handle, std::function<void(const FutureBase&)> callback,
      bool clear_existing_callbacks) = 0;
#endif  // defined(FIREBASE_USE_STD_FUNCTION)`

and also at every place where std::function is used 

I have made sure that we are using CXX STD greater than 11 and also we are including <functional>

There are some other errors like 

`/Users/Developer/MyProject/External/Firebase/iOS/firebase/internal/future_impl.h:303: error: variable has incomplete type 'void'
inline void FutureBase::OnCompletion(std::function<void(const FutureBase&)> callback) const
                        ^`

Can you please help?

**Comment by a-maurice** [comment]
Hi @k2ncore 

What compiler are you using?  The logic that defines FIREBASE_USE_STD_FUNCTION is just gated behind using STLPORT, which doesn't define functions, but you might be hitting another odd case.  If you don't need to use "function", you could disable it by modifying where it is set in app/src/include/firebase/internal/common.h, though ideally we can find a way to get this to work.

Have you tried getting one of the quickstarts, available at https://github.com/firebase/quickstart-cpp, to build and run?

**Comment by k2ncore** [comment]
Thanks a-maurice, disabling FIREBASE_USE_STD_FUNCTION resolves the function related problem. But it raises another issue of :
`error: symbol(s) not found for architecture x86_64`

Usually in Xcode projects we resolve this by setting build architecture to Build Active Architecture Only, but in CMake-QT projects I am clueless to make further progress. I got rid of all the not-required libraries but no luck.

Any help would be appreciated!!

**Comment by a-maurice** [comment]
What platform are you building for?  Unless you need to use the open source build for a reason, you could also try using the prebuilt version, which would likely have the architectures that you need.  Instructions for that can be found at https://firebase.google.com/docs/cpp/setup

**Comment by k2ncore** [comment]
We are prebuilt versions only and using the CMakeLists provided by firebase to make sure what all platforms are served. We want it to be done for all the platform iOS, android, Mac and PC.

**Comment by k2ncore** [comment]
Digging further into it, I came across some more pointers for this.

- This happens when I try to include firebase/analytics.h in my project's entry class
- This has something to do with the callback initializer for the analytics module or other modules (say admob)

[Code from common.h]

```
// Declare a module initializer variable as a global.
#define FIREBASE_APP_REGISTER_CALLBACKS_INITIALIZER_VARIABLE(module_name)     \
  namespace firebase {                                              \
  extern void* FIREBASE_APP_REGISTER_CALLBACKS_INITIALIZER_NAME(module_name); \
  } /* namespace firebase */

// Generates code which references a module initializer.
// For example, FIREBASE_APP_REGISTER_REFERENCE(analytics) will register the
// module initializer for the analytics module.
#define FIREBASE_APP_REGISTER_CALLBACKS_REFERENCE(module_name)        \
  FIREBASE_APP_REGISTER_CALLBACKS_INITIALIZER_VARIABLE(module_name)   \
  namespace firebase {                                      \
  static void* module_name##_ref FIREBASE_APP_KEEP_SYMBOL =           \
      &FIREBASE_APP_REGISTER_CALLBACKS_INITIALIZER_NAME(module_name); \
  }     /* namespace firebase */


```
The error details that I get are:

```
Undefined symbols for architecture x86_64:
  "firebase::g_analytics_initializer", referenced from:
      firebase::analytics_ref in libMyGameEntry.a(AppDelegate.mm.o)
      firebase::analytics_ref in libMyGameEntry.a(MyGameEntry.cpp.o)
      firebase::analytics_ref in libMyGameEntry.a(WindowDelegate.mm.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by k2ncore** [comment]
Here are the details of the development environment, OS version and compiler details:

**OS**: 						Mac OS Mojave 10.14.6
**IDE**: 					QT Creator 4.5.0 (i.e. based on Qt 5.10.0 Apple Clang 7.0, 64 Bit)
**Compiler**: 
						Apple LLVM version 10.0.1 (clang-1001.0.46.4) 
						Target: x86_64-apple-darwin18.7.0 
						Thread model: posix 
						InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
**CMake**:					cmake_3.8.2
**CMAKE_OSX_SYSROOT** :	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.17.sdk

The way I am trying to integrate Firebase is:

- Unzipped firebase-cpp-sdk in the external library folder of the project.
- Include the CMakelist from firebase to project
- #include “{Path to firebase-cpp-sdk}/include/firebase/analytics.h”
- Use the methods like Initialize Firebase and LogEvent (but I am not able to get to this step as the errors that I am getting are just after including 'analytics.h’)

Am I missing something here or doing this in some other order from what it is meant to be done?

Please let me know if anything else is needed from my end.

**Comment by k2ncore** [comment]
BUMP

**Comment by cynthiajoan** [comment]
Hi @k2ncore, we noticed you didn't mentioned that you've linked against firebase libraries. Please try add following lines to your CMakeList.txt
target_link_libraries(<your_target> firebase_app firebase_analytics)

You can take a look at our sample app [CMakeList.txt](https://github.com/firebase/quickstart-cpp/blob/master/analytics/testapp/CMakeLists.txt) as an example.

If that still not work, could you please provide your CMakeList for us to take a look?

Thanks!
