### ISSUE TITLE
Can't compile for Android (gradle)

### ISSUE THREAD

**Issue by johnbeforescott** [firebase/firebase-cpp-sdk#37]
### Please fill in the following fields:
Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: repo
Firebase C++ SDK version: latest
Firebase plugins in use (Auth, Database, etc.):
Additional SDKs you are using (Facebook, AdMob, etc.):  none
Platform you are using the C++ SDK on (Mac, Windows, or Linux):  Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

It must be something wrong with my setup, but I can't seem to compile the repo for Android using Gradle. When trying the following command: gradlew :app:assembleRelease I get the following build errors:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildRelease'.
> Build command failed.
  Error while executing process C:\Users\joscott\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\cmake.exe with arguments {--build C:\projects\firebase-cpp-sdk\app\.externalNativeBuild\cmake\release\x86_64 --target firebase_app}
  [1/50] Building CXX object external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/idl_parser.cpp.o
  FAILED: external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/idl_parser.cpp.o
  C:\Users\joscott\AppData\Local\Android\Sdk\ndk\20.1.5948944\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=x86_64-none-linux-android21 --gcc-toolchain=C:/Users/joscott/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/joscott/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot   -Iexternal/src/flatbuffers/include -Iexternal/src/flatbuffers/grpc -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -O2 -DNDEBUG  -fPIC   /Zc:__cplusplus -std=gnu++11 -MD -MT external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/idl_parser.cpp.o -MF external\src\flatbuffers-build\CMakeFiles\flatbuffers.dir\src\idl_parser.cpp.o.d -o external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/idl_parser.cpp.o -c external/src/flatbuffers/src/idl_parser.cpp
  clang++: error: no such file or directory: '/Zc:__cplusplus'
  [2/50] Building CXX object external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/idl_gen_text.cpp.o
  FAILED: external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/idl_gen_text.cpp.o
  C:\Users\joscott\AppData\Local\Android\Sdk\ndk\20.1.5948944\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=x86_64-none-linux-android21 --gcc-toolchain=C:/Users/joscott/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/joscott/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot   -Iexternal/src/flatbuffers/include -Iexternal/src/flatbuffers/grpc -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -O2 -DNDEBUG  -fPIC   /Zc:__cplusplus -std=gnu++11 -MD -MT external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/idl_gen_text.cpp.o -MF external\src\flatbuffers-build\CMakeFiles\flatbuffers.dir\src\idl_gen_text.cpp.o.d -o external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/idl_gen_text.cpp.o -c external/src/flatbuffers/src/idl_gen_text.cpp
  clang++: error: no such file or directory: '/Zc:__cplusplus'
  [3/50] Building CXX object external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/code_generators.cpp.o
  FAILED: external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/code_generators.cpp.o
  C:\Users\joscott\AppData\Local\Android\Sdk\ndk\20.1.5948944\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=x86_64-none-linux-android21 --gcc-toolchain=C:/Users/joscott/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/joscott/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot   -Iexternal/src/flatbuffers/include -Iexternal/src/flatbuffers/grpc -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -O2 -DNDEBUG  -fPIC   /Zc:__cplusplus -std=gnu++11 -MD -MT external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/code_generators.cpp.o -MF external\src\flatbuffers-build\CMakeFiles\flatbuffers.dir\src\code_generators.cpp.o.d -o external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/code_generators.cpp.o -c external/src/flatbuffers/src/code_generators.cpp
  clang++: error: no such file or directory: '/Zc:__cplusplus'
  [4/50] Building CXX object external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/reflection.cpp.o
  FAILED: external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/reflection.cpp.o
  C:\Users\joscott\AppData\Local\Android\Sdk\ndk\20.1.5948944\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=x86_64-none-linux-android21 --gcc-toolchain=C:/Users/joscott/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/joscott/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot   -Iexternal/src/flatbuffers/include -Iexternal/src/flatbuffers/grpc -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -O2 -DNDEBUG  -fPIC   /Zc:__cplusplus -std=gnu++11 -MD -MT external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/reflection.cpp.o -MF external\src\flatbuffers-build\CMakeFiles\flatbuffers.dir\src\reflection.cpp.o.d -o external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/reflection.cpp.o -c external/src/flatbuffers/src/reflection.cpp
  clang++: error: no such file or directory: '/Zc:__cplusplus'
  [5/50] Building CXX object external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/util.cpp.o
  FAILED: external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/util.cpp.o
  C:\Users\joscott\AppData\Local\Android\Sdk\ndk\20.1.5948944\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=x86_64-none-linux-android21 --gcc-toolchain=C:/Users/joscott/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/joscott/AppData/Local/Android/Sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/sysroot   -Iexternal/src/flatbuffers/include -Iexternal/src/flatbuffers/grpc -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -O2 -DNDEBUG  -fPIC   /Zc:__cplusplus -std=gnu++11 -MD -MT external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/util.cpp.o -MF external\src\flatbuffers-build\CMakeFiles\flatbuffers.dir\src\util.cpp.o.d -o external/src/flatbuffers-build/CMakeFiles/flatbuffers.dir/src/util.cpp.o -c external/src/flatbuffers/src/util.cpp
  clang++: error: no such file or directory: '/Zc:__cplusplus'
  [6/50] Building flatc (the FlatBuffer schema compiler)
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/projects/firebase-cpp-sdk/app/.externalNativeBuild/cmake/release/x86_64/external/src/flatbuffers-build-flatc
  Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
  Copyright (C) Microsoft Corporation. All rights reserved.

    flatc.vcxproj -> C:\projects\firebase-cpp-sdk\app\.externalNativeBuild\cmake\release\x86_64\external\src\flatbuffers-build-flatc\Debug\flatc.exe
  ninja: build stopped: subcommand failed.

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ?

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by chkuang-g** [comment]
Seems like this is messing around with Android build on Windows.
https://github.com/firebase/firebase-cpp-sdk/blob/master/CMakeLists.txt#L48

Could change this to "if(WIN32 AND NOT ANDROID)" and build it again?

Shawn

**Comment by johnbeforescott** [comment]
That didn't work either, kept trying to compile with that flag. 

If I comment out that line completely ("add_definitions("/Zc:__cplusplus")"), I can get it to compile though.  

Thanks for the help.
