### ISSUE TITLE
Ki[Question] 

### ISSUE THREAD

**Issue by fatih2807** [firebase/firebase-cpp-sdk#388]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: _____
  * Firebase C++ SDK version: _____
  * Main Firebase Components in concern: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: _____ (Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)

**Comment by chkuang-g** [comment]
@fatih2807 

This seems to be created accidentally.  I will close this for now.

If you really have a question, please fill up the template in the new one. :)
