### ISSUE TITLE
Load another ad on an interstitial fails with internal SDK error on iOS

### ISSUE THREAD

**Issue by berinhardt** [firebase/firebase-cpp-sdk#4]
The first interstitial (loaded after InitializeLastResult() completes) works fine, but if I try to load another ad on OnPresentationStateChanged(ad, kPresentationStateHidden) it fails with InternalSDKError

Only way I could make it work was by creating a new firebase::admob::InterstitialAd and load there, but it's a bit of a hassle. Is this intended behaviour?

**Comment by ericleich** [comment]
This is intended behavior of the underlying iOS Google Mobile Ads SDK. As noted in the [iOS interstitial developer docs](https://developers.google.com/admob/ios/interstitial#use_gadinterstitialdelegate_to_reload), interstitials are a 1-time use object.
