### ISSUE TITLE
Inproper define "#if INTERNAL_EXPERIMENTAL" should be changed to "#ifdef INTERNAL_EXPERIMENTAL"

### ISSUE THREAD

**Issue by crazyhappygame** [firebase/firebase-cpp-sdk#44]
### Please fill in the following fields:
Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: prebuild
Firebase C++ SDK version:  firebase_cpp_sdk_6.12.0
Firebase plugins in use (Auth, Database, etc.): Auth
Additional SDKs you are using (Facebook, AdMob, etc.): None
Platform you are using the C++ SDK on (Mac, Windows, or Linux): Any
Platform you are targeting (iOS, Android, and/or desktop): Any

### Please describe the issue here:
MSVC compile with: /W4
compilation warning
```
firebase_cpp_sdk\include\firebase/app.h(232,5): warning C4668: 'INTERNAL_EXPERIMENTAL' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
```
This is regression compare to 6.2.0
Problem:
Below line
```
#if INTERNAL_EXPERIMENTAL
```
Should be replaced with 
```
#ifdef INTERNAL_EXPERIMENTAL
```
### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ? yes

What's the issue repro rate? 100%

**Comment by a-maurice** [comment]
Thanks for alerting us of this, we will push a fix for this as soon as we can.

**Comment by chkuang-g** [comment]
@crazyhappygame 

The patch should be in master branch now
