### ISSUE TITLE
[Bug] Prebuild library firebase::auth not linking.

### ISSUE THREAD

**Issue by xhimanshuz** [firebase/firebase-cpp-sdk#441]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: _____
  * Firebase C++ SDK version: SDK 7.3.0
  * Problematic Firebase Component: Auth (Auth, Database, etc.)
  * Other Firebase Components in use: Auth (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: Linux (Mac, Windows, or Linux)
  * Platform you are targeting: desktop (iOS, Android, and/or desktop)

### [REQUIRED] Please describe the issue here:
When i try to compile simple firebase::auth program getting this error.

```
g++ main.cpp -I~/firebase_cpp_sdk/include  -lpthread -L~/firebase_cpp_sdk/libs/linux/x86_64/cxx11 -lfirebase_auth -lfirebase_app

/usr/bin/ld: /home/gnu/Downloads/firebase_cpp_sdk/libs/linux/x86_64/cxx11/libfirebase_app.a(2821dc7f0f996caf95294ccbe3bb0f98_user_secure_linux_internal.cc.o): in function `firebase::app::secure::UserSecureLinuxInternal::DeleteAllData()':
user_secure_linux_internal.cc:(.text+0xf3): undefined reference to `secret_password_clear_sync'
/usr/bin/ld: user_secure_linux_internal.cc:(.text+0x132): undefined reference to `g_error_free'
/usr/bin/ld: /home/gnu/Downloads/firebase_cpp_sdk/libs/linux/x86_64/cxx11/libfirebase_app.a(2821dc7f0f996caf95294ccbe3bb0f98_user_secure_linux_internal.cc.o): in function `firebase::app::secure::UserSecureLinuxInternal::DeleteUserData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
user_secure_linux_internal.cc:(.text+0x1ab): undefined reference to `secret_password_clear_sync'
/usr/bin/ld: user_secure_linux_internal.cc:(.text+0x1ed): undefined reference to `g_error_free'
/usr/bin/ld: /home/gnu/Downloads/firebase_cpp_sdk/libs/linux/x86_64/cxx11/libfirebase_app.a(2821dc7f0f996caf95294ccbe3bb0f98_user_secure_linux_internal.cc.o): in function `firebase::app::secure::UserSecureLinuxInternal::SaveUserData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
user_secure_linux_internal.cc:(.text+0x286): undefined reference to `secret_password_store_sync'
/usr/bin/ld: user_secure_linux_internal.cc:(.text+0x2ca): undefined reference to `g_error_free'
/usr/bin/ld: /home/gnu/Downloads/firebase_cpp_sdk/libs/linux/x86_64/cxx11/libfirebase_app.a(2821dc7f0f996caf95294ccbe3bb0f98_user_secure_linux_internal.cc.o): in function `firebase::app::secure::UserSecureLinuxInternal::LoadUserData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
user_secure_linux_internal.cc:(.text+0x39b): undefined reference to `secret_password_lookup_sync'
/usr/bin/ld: user_secure_linux_internal.cc:(.text+0x3be): undefined reference to `g_error_free'
/usr/bin/ld: user_secure_linux_internal.cc:(.text+0x488): undefined reference to `secret_password_free'
/usr/bin/ld: /home/gnu/Downloads/firebase_cpp_sdk/libs/linux/x86_64/cxx11/libfirebase_app.a(2821dc7f0f996caf95294ccbe3bb0f98_user_secure_linux_internal.cc.o): in function `firebase::app::secure::UserSecureLinuxInternal::CheckForError(_GError**, char const*)':
user_secure_linux_internal.cc:(.text+0x77c): undefined reference to `g_error_free'
collect2: error: ld returned 1 exit status
```
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:
Just add `#include <firebase/auth.h>` in your cpp file.

Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
Try to reproduce with prebuild 7.3.0.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:
```
#include <firebase/app.h>
#include <firebase/auth.h>  **// <-- when try to include auth header file.**
int main(int argc, const char * argv[]) 
{
    firebase::AppOptions option = firebase::AppOptions();
    firebase::App *app = firebase::App::Create(option);
    auto auth = firebase::auth::Auth::GetAuth(app); 
    return 0;
}
```

    g++ main.cpp -I~/firebase_cpp_sdk/include  -lpthread -L~/firebase_cpp_sdk/libs/linux/x86_64/cxx11 -lfirebase_auth -lfirebase_app
```
/usr/bin/ld: /home/gnu/Downloads/firebase_cpp_sdk/libs/linux/x86_64/cxx11/libfirebase_app.a(2821dc7f0f996caf95294ccbe3bb0f98_user_secure_linux_internal.cc.o): in function `firebase::app::secure::UserSecureLinuxInternal::DeleteAllData()':
user_secure_linux_internal.cc:(.text+0xf3): undefined reference to `secret_password_clear_sync'
/usr/bin/ld: user_secure_linux_internal.cc:(.text+0x132): undefined reference to `g_error_free'
/usr/bin/ld: /home/gnu/Downloads/firebase_cpp_sdk/libs/linux/x86_64/cxx11/libfirebase_app.a(2821dc7f0f996caf95294ccbe3bb0f98_user_secure_linux_internal.cc.o): in function `firebase::app::secure::UserSecureLinuxInternal::DeleteUserData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
user_secure_linux_internal.cc:(.text+0x1ab): undefined reference to `secret_password_clear_sync'
/usr/bin/ld: user_secure_linux_internal.cc:(.text+0x1ed): undefined reference to `g_error_free'
/usr/bin/ld: /home/gnu/Downloads/firebase_cpp_sdk/libs/linux/x86_64/cxx11/libfirebase_app.a(2821dc7f0f996caf95294ccbe3bb0f98_user_secure_linux_internal.cc.o): in function `firebase::app::secure::UserSecureLinuxInternal::SaveUserData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
user_secure_linux_internal.cc:(.text+0x286): undefined reference to `secret_password_store_sync'
/usr/bin/ld: user_secure_linux_internal.cc:(.text+0x2ca): undefined reference to `g_error_free'
/usr/bin/ld: /home/gnu/Downloads/firebase_cpp_sdk/libs/linux/x86_64/cxx11/libfirebase_app.a(2821dc7f0f996caf95294ccbe3bb0f98_user_secure_linux_internal.cc.o): in function `firebase::app::secure::UserSecureLinuxInternal::LoadUserData(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
user_secure_linux_internal.cc:(.text+0x39b): undefined reference to `secret_password_lookup_sync'
/usr/bin/ld: user_secure_linux_internal.cc:(.text+0x3be): undefined reference to `g_error_free'
/usr/bin/ld: user_secure_linux_internal.cc:(.text+0x488): undefined reference to `secret_password_free'
/usr/bin/ld: /home/gnu/Downloads/firebase_cpp_sdk/libs/linux/x86_64/cxx11/libfirebase_app.a(2821dc7f0f996caf95294ccbe3bb0f98_user_secure_linux_internal.cc.o): in function `firebase::app::secure::UserSecureLinuxInternal::CheckForError(_GError**, char const*)':
user_secure_linux_internal.cc:(.text+0x77c): undefined reference to `g_error_free'
```

**Comment by alexames** [comment]
It looks like you're not linking against libsecret, which is necessary on the Linux desktop implementation. Normally when you build through CMake it would link against it for your or raise an error if it wasn't available, but since you're building directly from the command line you didn't get that error.

Take a look at this for more information:

https://github.com/firebase/firebase-cpp-sdk/blob/7d6d8c9/release_build_files/CMakeLists.txt#L111

**Comment by xhimanshuz** [comment]
I'm not linking it but look like it is already build with libsecret or maybe a dependency, maybe I have to link libsecret before linking firebase_auth.

**Comment by chkuang-g** [comment]
@xhimanshuz 

Please let us know if it works if you link `libsecret`.

**Comment by xhimanshuz** [comment]
I tried to link with `g++  -o CppTest main.o   -lssl -lcrypto **-lsecret-1** -L/home/gnu/Downloads/firebase_cpp_sdk/libs/linux/x86_64/cxx11 -lfirebase_analytics -lfirebase_auth -lfirebase_database -lfirebase_app /usr/lib/libQt5Gui.so /usr/lib/libQt5Core.so -lGL -lpthread  `
Added a **libsecret-1**, This error was occurring previously too.

```
/usr/bin/ld: /home/gnu/Downloads/firebase_cpp_sdk/libs/linux/x86_64/cxx11/libfirebase_app.a(2821dc7f0f996caf95294ccbe3bb0f98_user_secure_linux_internal.cc.o): undefined reference to symbol 'g_error_free'
/usr/bin/ld: /usr/lib/libglib-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by chkuang-g** [comment]
`g_error_free()` is a glib library.

As mentioned in [this doc](https://firebase.google.com/docs/cpp/setup?platform=android#linux-libraries), if you are using GCC 5 or later, try to add `-D_GLIBCXX_USE_CXX11_ABI=0`.

Let us know if this works for you

**Comment by xhimanshuz** [comment]
**Compiling**
`g++ -c -Wall -D_GLIBCXX_USE_CXX11_ABI=0 -I. -I../../../../Downloads/firebase_cpp_sdk/include  -I. -o main.o main.cpp`
**Linking**
`g++ -o CppTest main.o -lpthread -lsecret-1  -L/home/gnu/Downloads/firebase_cpp_sdk/libs/linux/x86_64/cxx11 -lfirebase_analytics -lfirebase_auth -lfirebase_database -lfirebase_app`
**Error Output:**
`/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../lib/libsecret-1.so: undefined reference to symbol 'g_error_free'
/usr/bin/ld: /usr/lib/libglib-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status`
Still not working, M'I doing it right?
**Compiler Info**
**$ g++ -v**
`Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC) `

**Comment by xhimanshuz** [comment]
One more thing to mention, Even I build firebase-cpp-sdk from source on my system. Still facing the same issue.

`$ g++  -o CppTest main.o   -lpthread -lssl -lcrypto -L/home/gnu/firebase -lfirebase_analytics -lfirebase_auth -lfirebase_database -lfirebase_app -lsecret-1   `
```
/usr/bin/ld: /home/gnu/firebase/libfirebase_app.a(user_secure_linux_internal.cc.o): undefined reference to symbol 'g_error_free'
/usr/bin/ld: /usr/lib/libglib-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by vimanyu** [comment]
Hi,
So I tried building your original example (with the `main.cpp` provided) and I could successfully build it with the following command,
```
g++ main.cpp -I<firebase_cpp_sdk>/include -L<firebase_cpp_sdk>/libs/linux/x86_64/cxx11 -lfirebase_auth -lfirebase_app -lpthread -lglib-2.0 -lsecret-1
```
`g_error_free` is a symbol that can be found in glib-2.0 library. Please use the package manager to install glib-2.0 if it is missing on your system.

Another note is that the order of libraries linked matters. In general, if library A depends on library B which inturn depends on library C, the linker order should be `-lA -lB -lC`

In your last example, I will recommend placing firebase_app after all the other firebase libraries and the system libraries (pthread, ssl etc) after firebase_app.

**Comment by xhimanshuz** [comment]
Thanks, Linking in order will work, after putting dependencies at the last.
