### ISSUE TITLE
[Question] Linker errors when using Auth with qmake on Ubuntu

### ISSUE THREAD

**Issue by trufanov-w** [firebase/firebase-cpp-sdk#449]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: website & github repo
  * Firebase C++ SDK version: 7.3.0
  * Main Firebase Components in concern: Firestore
  * Other Firebase Components in use: Auth
  * Platform you are using the C++ SDK on: Linux (Ubuntu 18.04)
  * Platform you are targeting: desktop

### [REQUIRED] Please describe the question here:

I am using ready-made libraries SDK 7.3.0 under Ubuntu 18.04 with QT 5.9.7
Building a project from the quickstart-cpp example
Added the include and libs folder to the project
In * .pro file added

```
INCLUDEPATH += $$PWD/include

LIBS += -lpthread
LIBS += -L$$PWD/libs/linux/x86_64/cxx11 -lfirebase_app
LIBS += -L$$PWD/libs/linux/x86_64/cxx11 -lfirebase_auth
LIBS += -L$$PWD/libs/linux/x86_64/cxx11 -lfirebase_firestore
LIBS += -L$$PWD/libs/linux/x86_64/cxx11 -lfirebase_functions
```

In min.pp added

```
#include "firebase/auth.h"
#include "firebase/auth/user.h"
#include "firebase/firestore.h"
#include "firebase/util.h"
```

When assembling, I immediately received a bunch of errors:
```
idl_parser.cpp:-1: ошибка: undefined reference to `std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
/home/local/Develop/Firestore4/libs/linux/x86_64/legacy/libfirebase_app.a(4ccfc2a628bf97c8d3e7d7ec77d31206_idl_parser.cpp.o): In function `std::string f_b_flatbuffers::TypeToIntervalString<short>()':
idl_parser.cpp:(.text._ZN11flatbuffers20TypeToIntervalStringIsEESsv[_ZN15f_b_flatbuffers20TypeToIntervalStringIsEESsv]+0x3b): undefined reference to `std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'

auth_desktop.cc:-1: error: undefined reference to `firebase :: Thread :: Thread () '
/home/local/Develop/Firestore4/libs/linux/x86_64/legacy/libfirebase_auth.a(9b788918c2ba0e0ffaefa78515169526_auth_desktop.cc.o): In function `firebase :: auth :: CreatePlatformAuth * (firebase :: auth :: CreatePlatformAuth *)
auth_desktop.cc:(.text+0xed4): undefined reference to `firebase :: Thread :: Thread () ' 

/home/local/Develop/Firestore4/libs/linux/x86_64/legacy/libfirebase_auth.a(9b788918c2ba0e0ffaefa78515169526_auth_desktop.cc.o):-1: error: undefined reference to `typeinfo for firebase::rest::Response'
```

and others related to auth_desktop.cc, auth_util.cc, user_desktop.cc and other files.
Errors appear when adding 
```
#include "firebase/auth.h"
```

Tried using libraries from folder1 and folder2
also turned -D_GLIBCXX_USE_CXX11_ABI on and off, but nothing changed

**Comment by var-const** [comment]
(I changed the title because it doesn't seem this is actually related to Firestore -- hope you don't mind the change)

**Comment by chkuang-g** [comment]
@trufanov-w 

Just to confirm if you are using `qmake` to build your application. Also, you were able to build without `#include "firebase/auth.h"`.
We never build with `qmake` before so there might be some quirks related to this.

Could you provide us with a minimum viable project and reproduction steps to work with? 

Shawn

**Comment by vimanyu** [comment]
Can you try using the following order for linked libraries,
```
LIBS += -L$$PWD/libs/linux/x86_64/cxx11 -lfirebase_firestore
LIBS += -L$$PWD/libs/linux/x86_64/cxx11 -lfirebase_functions
LIBS += -L$$PWD/libs/linux/x86_64/cxx11 -lfirebase_auth
LIBS += -L$$PWD/libs/linux/x86_64/cxx11 -lfirebase_app
LIBS += -lpthread
```
