### ISSUE TITLE
Authentication through service-account

### ISSUE THREAD

**Issue by hbgxsm95** [firebase/firebase-cpp-sdk#45]
### Please fill in the following fields:
Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo:
Firebase C++ SDK version: latest
Firebase plugins in use (Auth, Database, etc.): Auth
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the C++ SDK on (Mac, Windows, or Linux):  Mac
Platform you are targeting (iOS, Android, and/or desktop): Desktop

### Please describe the issue here:

Currently the way to authenticate api access is to set api-key in AppOptions. Is it possible that we could also have support for initialization based on service account like Java, Go and python sdk?

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ?

Yes

What's the issue repro rate? (eg 100%, 1/5 etc)

100%

**Comment by morganchen12** [comment]
The SDKs you mentioned are all admin SDKs intended to run in trusted execution environments (servers), so they have higher privileges than the client SDKs. This is why you cannot authenticate API access with a service account on the client SDKs and we recommend against using the admin SDKs in a client application.
