### ISSUE TITLE
[Question] ABSL: compiling absl requires a gtest CMake target in your project

### ISSUE THREAD

**Issue by vadbut** [firebase/firebase-cpp-sdk#453]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: from the repo
  * Firebase C++ SDK version: used the latest commit 461479d6b98ee825b757d4071f269a576fe28d04
  * Main Firebase Components in concern: build with VS2019
  * Other Firebase Components in use: N/A
  * Platform you are using the C++ SDK on: Windows
  * Platform you are targeting: desktop

### [REQUIRED] Please describe the question here:
I'm working in VS2019 on a minimal project that builds and links firebase.
CMakeLists.txt looks as following:
```
cmake_minimum_required (VERSION 3.8)

project ("test_proj")

find_package(PythonInterp)
set(FIREBASE_CPP_SDK_DIR ${CMAKE_CURRENT_SOURCE_DIR}/external/firebase-cpp-sdk)
add_subdirectory(${FIREBASE_CPP_SDK_DIR})

set(SOURCES
    src/main.cpp
)

add_executable(buffr ${SOURCES})

target_include_directories(test_proj PRIVATE ${PROJECT_SOURCE_DIR}/include)

target_link_libraries(test_proj
    firebase_app
    firebase_auth
)
```

CMake spits out the following error:

> CMake Error at out/build/x64-Debug/external/firebase-cpp-sdk/external/src/firestore-build/external/src/abseil-cpp/CMake/AbseilHelpers.cmake:350 (message):
> ABSL: compiling absl requires a gtest CMake target in your project, see CMake/README.md for more details

- I checked the readme file in /firestore and didn't find any special instructions for Windows.
- Just in case, I checked that my VS2019 came with installed gtest adapter.

How can I bypass the issue, is it possible to just disable the unit tests?

**Comment by vimanyu** [comment]
Hi, 
Thank you for creating this issue and providing a minimal example. Ideally, we shouldn't be running into this error and will dig deeper into it but I think you can work around it for now by specifying the cmake option `-DFIREBASE_INCLUDE_FIRESTORE=OFF` during your cmake configure command.
This will prevent any cmake configuration for Firestore and won't try to download and build its dependencies. 

Firebase C++ unit tests are controlled by the option `FIREBASE_CPP_BUILD_TESTS` but that should be OFF by default. 

```
$ cmake -DFIREBASE_INCLUDE_FIRESTORE=OFF <source_dir>
```

**Comment by dconeybe** [comment]
There are two workarounds for this bug that we use internally at Google on the Firestore SDK team: specify one of

1. `-DFIREBASE_CPP_BUILD_TESTS=ON`
2. `-DBUILD_TESTING=off`

to the `cmake` command. There is a very similar issue in grpc: https://github.com/grpc/grpc/issues/24143.

**Comment by vadbut** [comment]
Both suggestions are valid. Thank you.
