### ISSUE TITLE
[Question] google-services.json for a desktop app

### ISSUE THREAD

**Issue by vadbut** [firebase/firebase-cpp-sdk#455]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: latest repo
  * Firebase C++ SDK version: latest commit
  * Main Firebase Components in concern: Project Settings/Configuration
  * Other Firebase Components in use: Auth
  * Platform you are using the C++ SDK on: Windows
  * Platform you are targeting: Desktop

### [REQUIRED] Please describe the question here:

For my project, I'd like to set up only a web application (which I did without any problem) and a Windows desktop app. I don't intend to create an Android or iOS app.
Based on README and articles I found (https://medium.com/firebase-developers/how-to-add-firebase-to-your-c-desktop-game-4a177703186e) it appears that for a desktop Windows app I still need to provide a json config file that is normally created for an Android app (or obtained from an iOS plist).

Can you pls clarify the following:
1. I acknowledge the disclaimer about the limited functionality beta version of Firebase C++, however, based on README and articles it seemed to me that C++ Firebase in its current form should already support my use case (a project without an Android or iOS app). Please clarify if I misunderstood it and having an Android or iOS app is a must.
2. If "yes" to (1) (my use case is supported), then is google-services.json the way to configure my Desktop app that has nothing to do with Android or iOS?
3. If "yes" to (2), how can I generate such a json file? Should I create a dummy Android project in the Firebase console?

**Comment by chkuang-g** [comment]
@vadbut 

1. Currently we do not have a `desktop` Firebase config (part of the reason why it is still in beta).  As a result, C++/Unity desktop implementation reuse Firebase config for `Android`, a.k.a `google-services.json`.  You will still need to create an Android "app" on Firebase console for desktop application.  
1. Yes. However, I _think_ `google-services.json` is optional as long as you create your FirebaseApp with proper AppOptions, with app id, API key, etc.  See [App::Create( const AppOptions & options)](https://firebase.google.com/docs/reference/cpp/class/firebase/app#classfirebase_1_1_app_1ad78221c68b6e2aec107a090b28a8b80e) and [AppOptions](https://firebase.google.com/docs/reference/cpp/class/firebase/app-options#classfirebase_1_1_app_options). 
1. You can create a "dummy" Android app.

Hope this helps :)

**Comment by vadbut** [comment]
Thanks, that helped. Specifying AppOptions properly got it to work without a need to have a json file.
