### ISSUE TITLE
Unable to compile the SDK on windows/Linux

### ISSUE THREAD

**Issue by sandeepReddyG** [firebase/firebase-cpp-sdk#49]
### Please fill in the following fields:
open-source from this repo:
Firebase C++ SDK version: master  
Firebase plugins in use (Auth, Database, etc.): None
Additional SDKs you are using (Facebook, AdMob, etc.):None 
Platform you are using the C++ SDK on (Mac, Windows, or Linux): Windows 
Platform you are targeting (iOS, Android, and/or desktop): Windows Desktop

### Please describe the issue here:
I have downloaded the SDK from github and trying to compile it as per the mentioned instructions using Visual studio code .But I am facing compiler missing issue below

```
$ cmake ..
-- Building for: NMake Makefiles
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:75 (enable_language):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/Users/shiva/Downloads/Sandeep/firebase-cpp-sdk-master/fcm_build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/shiva/Downloads/Sandeep/firebase-cpp-sdk-master/fcm_build/CMakeFiles/CMakeError.log".
```

Actually , I want to understand that Messaging can be used with Desktop applications in Linux or not. If yes, could you please share me the steps to compile the sdk and sample app to receive Firebase Cloud Messaging in linux. 
Also let me know if this is not the SDK meant for Desktops ,how can I achieve Messaging for Desktops?

**Comment by morganchen12** [comment]
Have you tried the solution suggested in the error message?

>To fix this problem, run cmake from the Visual Studio Command Prompt (vcvarsall.bat).

Also, from what I understand Messaging is not available on Linux Desktop, but @a-maurice can confirm.

**Comment by a-maurice** [comment]
Messaging is not available on any of the desktop platforms, unfortunately, and instead builds stubbed implementations in it's place, so that it can still cross-compile.

**Comment by sandeepReddyG** [comment]
cross-compile for Android & IOS platforms only or any other platforms it supports ? Is Desktop SDK available in any other languages like Java , python etc.?

**Comment by morganchen12** [comment]
Cross-compile in this case means Messaging will compile on Linux but will not work (you can't actually receive messages on Linux desktop).

There are no desktop client SDKs besides Unity and C++ available currently.

**Comment by sandeepReddyG** [comment]
So , if we implement messaging functionality then this can be used to receive messaging in Desktop?

**Comment by morganchen12** [comment]
If you are feeling adventurous, you can wrap the iOS SDK's community-supported macOS and macOS Catalyst push notifications in a C++ API. But this is not easy and not supported by default.

Other than that, there is no Messaging support for desktop clients.

**Comment by sandeepReddyG** [comment]
Documents say firebase  is open source, but when I tried to understand the internals of Messaging most details are abstracted out like Token generation and host details where these services are hosted.Are these details confidential ? Does firebase client server communication uses GRPC and Protobuf? If so why server reflection is disabled for these services ,I can find server reflection enabled for only firebaseinappmessaging.googleapis.com.

**Comment by morganchen12** [comment]
Token generation varies by platform since it's somewhat coupled to each platform's messaging mechanism. For example, on iOS Messaging tokens are associated with APNs tokens, which are generated by the system. The abstraction in the C++ SDK is necessary to present a uniform cross-platform API, since the platform-specific details should only be exposed when absolutely necessary.

FCM's Android implementation is not open source, but here is the iOS implementation: [firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk/tree/master/Firebase/Messaging)

**Comment by chkuang-g** [comment]
@sandeepReddyG 

Does this answer your question?  Please let us know.
