### ISSUE TITLE
[Analytics] ParamName not displaying correctly

### ISSUE THREAD

**Issue by GloryOfNight** [firebase/firebase-cpp-sdk#5]
Hi! I having some issue with displaying correct parameter name in Firebase console. 
Here of my code example: [Link](https://github.com/GloryOfNight/UE4FirebaseAnalytics/blob/85524cc7390a47410cac947d00fd76b252a1ea5d/Source/FirebaseAnalytics/Private/FirebaseAnalyticsBPLib.cpp#L142-L153)

That a free firebase analytics provider for Unreal Engine 4.
So. About issue:

After sending event to firebase i looking for streamview and see event structure:
Category -> Category -> ParamValue

Expected structure:
Category -> ParamName -> ParamValue

For some reason, parameter name replaced with my category. (i know that string Category != ParamName). Any ideas what went wrong?

**Comment by ryanmeier** [comment]
Hi @GloryOfNight!  Could you provide some additional information to help figure out what might be causing your issue:
-Which version of the C++ SDK are you using?
-What platform was your application running on when sending these events?
-Are you able to reproduce the issue in the [Firebase Analytics Testapp](https://github.com/firebase/quickstart-cpp/tree/master/analytics/testapp)?

Thanks!

**Comment by GloryOfNight** [comment]
Sorry, problem was solved just by it self. I do not know what exact happen, but it's gone. Thanks.
