### ISSUE TITLE
Unable to compile the c++ SDK with Cmake on Mac | target == iOS

### ISSUE THREAD

**Issue by schramm** [firebase/firebase-cpp-sdk#52]
### Please fill in the following fields:
Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo:
Open source from:   https://github.com/firebase/firebase-cpp-sdk.git

Firebase C++ SDK version:   firebase_cpp_sdk_6.12.0 
Firebase plugins in use (Auth, Database, etc.): Auth
Additional SDKs you are using (Facebook, AdMob, etc.):  none
Platform you are using the C++ SDK on (Mac, Windows, or Linux):  Mac  
Platform you are targeting (iOS, Android, and/or desktop):   iOS

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

I am trying to build firebase-cpp-sdk using  CMake on MacOSX, targeting  iOS.

When I run:   cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/ios.cmake ..
I get the following error: 

[100%] Built target protobuf
-- Failed to find LLVM FileCheck
-- git Version: v0.0.0
-- Version: 0.0.0
-- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES -- failed to compile
-- Performing Test HAVE_STD_REGEX -- compiled but failed to run
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- compiled but failed to run
CMake Error at ios_build/external/src/firestore-build/external/src/benchmark/CMakeLists.txt:251 (message):
  Failed to determine the source files for the regular expression backend
From the CMakeError.log: 

Run Build Command(s):/usr/bin/make cmTC_fe8f5/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_fe8f5.dir/build.make CMakeFiles/cmTC_fe8f5.dir/build
Building CXX object CMakeFiles/cmTC_fe8f5.dir/src.cxx.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++    -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -Wshorten-64-to-32  -fstrict-aliasing  -Wno-deprecated-declarations  -fno-exceptions  -Wstrict-aliasing -DHAVE_CXX_FLAG_WD654  -wd654 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk   -wd654 -o CMakeFiles/cmTC_fe8f5.dir/src.cxx.o -c /Users/schramm/Desktop/firebase-cpp-sdk/ios_build/CMakeFiles/CMakeTmp/src.cxx
clang: error: unknown argument: '-wd654'
clang: error: unknown argument: '-wd654'
make[1]: *** [CMakeFiles/cmTC_fe8f5.dir/src.cxx.o] Error 1
make: *** [cmTC_fe8f5/fast] Error 2

Can anyone help me?

**Comment by patm1987** [comment]
Hi @schramm ,

After some investigation, I've reproduced your issue so the team is tracking it. In the meantime, I have a workaround that will work if you're not using Firestore:

First, updating to the latest Firebase SDK (6.15) will get you to a better state (your cmake command will work) but there will still be a build issue. To build without Firestore support (the library that's currently failing), run:
```
cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/ios.cmake -DFIREBASE_INCLUDE_FIRESTORE=OFF ..
```

If you do need Firestore support, the team is actively investigating the issue. The [binary distribution](https://firebase.google.com/docs/cpp/setup?platform=ios#add-sdks) should work if you need Firestore support on iOS (and can act as a drop-in replacement in CMake).

I hope that helps!

**Comment by schramm** [comment]
Hi @patm1987. Thanks a lot. I just tried to build firebase using cmake and it worked without any issues.
