### ISSUE TITLE
[Bug] Firestore uncondionally build main function

### ISSUE THREAD

**Issue by canatella** [firebase/firebase-cpp-sdk#537]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: open-source
  * Firebase C++ SDK version: 8.1.0
  * Problematic Firebase Component: Firestore (Auth, Database, etc.)
  * Other Firebase Components in use: Auth, Firestore (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: Linux (Mac, Windows, or Linux)
  * Platform you are targeting: Desktop (iOS, Android, and/or desktop)

### [REQUIRED] Please describe the issue here:

Firestore unconditionally builds a `main()` function: https://github.com/firebase/firebase-cpp-sdk/blob/ccee89c59f0bdafc419a4177c1782fef8025f2dd/firestore/CMakeLists.txt#L42 
This breaks desktop applications.

#### Steps to reproduce:

Build an executable with a `main()` function and link against firestore

**Comment by alexames** [comment]
That looks like some leftover cruft from when we were doing builds a little different. I don't think there's any good reason for it to be there. I got rid of it in #546. I'm going to close this, feel free to reopen if the issue persists.
