### ISSUE TITLE
How to compile firebase c++ SDK library for macos and tvos

### ISSUE THREAD

**Issue by newonelei** [firebase/firebase-cpp-sdk#58]
does anyone have experience of building macos and tvos? Please help share it, thanks.

**Comment by dconeybe** [comment]
Hello @newonelei. Unfortunately, this is not the correct venue for your question. This issue tracker is for reporting and managing bugs in the code. There are, however, several venues at your disposal for asking questions like this. See https://firebase.google.com/support, where options like StackOverflow and Google Groups are presented. All the best!
