### ISSUE TITLE
[Question] use firebase in Visual Studio 2019 project

### ISSUE THREAD

**Issue by doczoidberg** [firebase/firebase-cpp-sdk#588]
I need firebase in my VS C++ Winforms desktop application. 

As stated here: https://firebase.google.com/docs/cpp/setup?platform=android#ndk-build

One need CMake. Is this really needed or is it enough to add libs and headers to my VS2019 project?

**Comment by HODAKdev** [comment]
I tried it, I added Firebase include and libs to the project and I connected(or use #pragma comment(lib, "...") it all but I get an unresolved external symbol ... (83x).
I added -
```
#include "firebase/app.h"
#include "firebase/auth.h" 
```
with **no code**, it still didn't work wtf.
I used a lot of tools that needed libs and it was easy but I don't know what's going on with that it :(

**Comment by HODAKdev** [comment]
yeah aha so firebase needs these too https://github.com/firebase/firebase-cpp-sdk/issues/32#issuecomment-555942217
