### ISSUE TITLE
use firebase in Visual Studio 2013 project

### ISSUE THREAD

**Issue by xiaonaiquan** [firebase/firebase-cpp-sdk#591]
Can I use the SDK you provide in Visual Studio 2013? I only see 2019 in the SDK compression package.

**Comment by DellaBitta** [comment]
Hi @xianaiquan,

Based on [Microsoft's documentation](VisualStudio2019), linking these libraries with Visual 2013 might be a risky propsect.

We haven't tested on 2013 in a while, so I'm not sure how well it compiles with that toolchain.  But good news!  We're fully open source now so you can try it to build the libraries youself using our cmake build steps documented in the repo.

**Comment by xiaonaiquan** [comment]
> Hi @xianaiquan,
> 
> Based on [Microsoft's documentation](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-160), linking these libraries with Visual 2013 might be a risky propsect.
> 
> We haven't tested on 2013 in a while, so I'm not sure how well it compiles with that toolchain. But good news! We're fully open source now so you can try it to build the libraries youself using our cmake build steps documented in the repo.

OK , Thanks. I'll try to compile it.
