### ISSUE TITLE
How to download firebase cpp sdk older version

### ISSUE THREAD

**Issue by Yosef0109** [firebase/firebase-cpp-sdk#64]
I want to download firebase cpp sdk v4.2.0. I can't find it anywhere. How can I download it?

**Comment by a-maurice** [comment]
You should be able to download it at: https://dl.google.com/firebase/sdk/cpp/firebase_cpp_sdk_4.2.0.zip

Note you can change that last bit to get different versions.

**Comment by Yosef0109** [comment]
Thanks @a-maurice for providing the firebase_cpp_sdk 4.2.0 :)
