### ISSUE TITLE
[Question] When will the Performance API officially be released?

### ISSUE THREAD

**Issue by PaulSchaetzle** [firebase/firebase-cpp-sdk#671]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: both
  * Firebase C++ SDK version: 8.5.0
  * Main Firebase Components in concern: Performance (Auth, Database, etc.)
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: Mac, Windows, Linux
  * Platform you are targeting: iOS, Android

### [REQUIRED] Please describe the question here:
Hi,

the company I am working at uses Qt/C++ in combination with the C++ firebase sdk to build Android/iOS apps.
We are very interested in the Performance API which is not included in the official releases. 
I noticed that the source code seems to be included in this repo and after some tinkering with CMakeLists and build.gradle
files I was able to build a (seemingly) working version. 
Since the source code seems to be working fine, when will the official release include Performance support? I unfortunately was not able to find any information about a roadmap or release date. 
We are looking forward to you answer.

Best regards 
Paul Schaetzle

**Comment by DellaBitta** [comment]
Hi @PaulSchaetzle,

The current plan is that the Performance API in this SDK will be be an unofficial /  community-supported feature.  

We haven't finalized the ability for the community to build and support this feature, however, as you've noticed.  If you indeed have it building and its working, could you submit a PR so that others may also use it?  Thanks!

**Comment by gwaldvogel** [comment]
> We haven't finalized the ability for the community to build and support this feature, however, as you've noticed. If you indeed have it building and its working, could you submit a PR so that others may also use it? Thanks!

In case someone provides said pull request, would the module be part of the official prebuilt releases in the future?

**Comment by DellaBitta** [comment]
Hi @gwaldvogel,

In the immediate future it will be a community supported feature in source form only and not part of our packaged releases.  Later it might become an officially supported part of the product and therefore be incorportated in the prebuilt libraries that we create and test, but that would depend on the level of maintence it requires and the module's popularity.
