### ISSUE TITLE
NOT WORKING REMOTE_CONFIG ANDROID !!!!!!!!!!!ksdjlabv

### ISSUE THREAD

**Issue by kaizer1** [firebase/firebase-cpp-sdk#70]
Firebase C++ SDK version: firebase_cpp_sdk 6.15.0
Firebase plugins in use (Auth, Database, etc.): remote_config
Additional SDKs you are using (Facebook, AdMob, etc.):  not, only use remote_config
Platform you are using the C++ SDK on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop):  Android 

### Please describe the issue here:
Here I have a simple example - there is a config on firewire and now all I need to do is get one value through the config remot - SO THAT !!! I CAN NOT DO IT !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  What am I doing wrong ????
  And damn, how terribly written the tutorials - nothing is intelligible and at least a little explaining what and how is done here !!

```
     ::firebase::App* app;
    app = ::firebase::App::Create(env, thiz);

    ::firebase::ModuleInitializer initializer;
    initializer.Initialize(app, nullptr, [](::firebase::App* app, void*){
        runLogging(" thiss initialize \n");
        return ::firebase::remote_config::Initialize(*app);
    });

    while(initializer.InitializeLastResult().status() != firebase::kFutureStatusComplete){
        runLogging(" hhhhh hhh h \n");
    }
    if(initializer.InitializeLastResult().error() != 0){
        runLogging(" my mistake init == %s \n", initializer.InitializeLastResult().error_message());
    }
    auto future_result = firebase::remote_config::Fetch(0);



  std::future_status status;
    do {
      //  status = future.wait_for(std::chrono::seconds(2));
        if (future_result.status() == firebase::kFutureStatusInvalid) {
            const firebase::remote_config::ConfigInfo& info = firebase::remote_config::GetInfo();
            if(info.last_fetch_failure_reason == firebase::remote_config::kFetchFailureReasonError){
            }else if (info.last_fetch_failure_reason == firebase::remote_config::kFetchFailureReasonInvalid){
            }else if(info.last_fetch_failure_reason == firebase::remote_config::kFetchFailureReasonThrottled){
            }else{
            }

        } else if (future_result.status() == firebase::kFutureStatusPending) {

           const firebase::remote_config::ConfigInfo& info = firebase::remote_config::GetInfo();
           
//
             if(info.last_fetch_failure_reason == firebase::remote_config::kFetchFailureReasonError){
                // runLogging(" kFetchFailureReasonError \n");
             }else if (info.last_fetch_failure_reason == firebase::remote_config::kFetchFailureReasonInvalid){
                 //runLogging(" kFetchFailureReasonInvalid \n");
             }else if(info.last_fetch_failure_reason == firebase::remote_config::kFetchFailureReasonThrottled){
                // runLogging(" kFetchFailureReasonThrottled \n");
             }else{
              //   runLogging(" another error  \n");
             }

        } else if (future_result.status() == firebase::kFutureStatusComplete) {
            runLogging(" ready AAAA \n");
        }
    } while (future_result.status() != firebase::kFutureStatusComplete);
```

Absolutely always ABSOLUTELY ALWAYS it hangs on kFutureStatusPending  
And does not go further. It does not get the value - firebase :: remote_config :: kFetchFailureReasonError error

I have a simple question - how, how can such a simple service be made so terrible ?????
 

What's the issue repro rate? (eg 100%, 1/5 etc) - I do not understand the question

**Comment by kaizer1** [comment]
I made sure and everything matches

**Comment by morganchen12** [comment]
The Windows Remote Config implementation is currently a stub and should only be used to verify your build.

You can find a working example using Remote Config in the [quickstart repository](https://github.com/firebase/quickstart-cpp/tree/master/remote_config/testapp). Also, next time please fill out the issue template correctly and avoid adding garbage language to your issue body.
