### ISSUE TITLE
AdvertisingIdentifierString reason for apple rejection

### ISSUE THREAD

**Issue by thienphuoc** [firebase/firebase-cpp-sdk#75]
### Please fill in the following fields:
Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo:
Firebase C++ SDK version: 6.14.0
Firebase plugins in use (Auth, Database, etc.): Auth, Database, Analytics, DynamicLinks, RemoteConfig 
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, GoogleSignIn
Platform you are using the C++ SDK on (Mac, Windows, or Linux): Mac, Windows
Platform you are targeting (iOS, Android, and/or desktop): Ios, Android

### Please describe the issue here:

Hi Firebase Team !

Currently, I'm facing the same problem as described here https://github.com/firebase/firebase-ios-sdk/issues/5153

As I know, the new version of FirebaseAnalytics (6.27.1) has been released for IOS SDK to solve this problem.

And Each version of the Firebase C++ SDK supports a specific version of the Firebase iOS SDK.

To solve this problem temporarily, Can I use Cocoapod versions listed below for **Firebase C++ SDK 6.14.0(or 6.15.1)**.

![Screen Shot 2020-07-08 at 11 44 26](https://user-images.githubusercontent.com/17909394/86877162-7385af80-c110-11ea-9fb8-c04c3a3cb665.png)

Could the firebase team help me to release the new version for C++ SDK?

Thanks 

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ? N/A

What's the issue repro rate? (eg 100%, 1/5 etc) 
100%

**Comment by chkuang-g** [comment]
@thienphuoc 

I did notice that Pod SDK version has not been updated for quite awhile.  I'll ping the team about this.

Thank you for reporting this!

**Comment by chkuang-g** [comment]
Hi,

I think Analytics team introduced pod without AdsId in it.

Please see this https://github.com/firebase/quickstart-unity/issues/994#issuecomment-825922406 and update the `Podfile` accordingly.

Shawn
