### ISSUE TITLE
[Question] Tracking the Windows Desktop Application (WPF+C#) using Analytics.lib for Google Analytics.

### ISSUE THREAD

**Issue by DeepakHirapur** [firebase/firebase-cpp-sdk#750]
* Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: Pre-built SDK
  * Firebase C++ SDK version: 8.7
  * Main Firebase Components in concern: Analytics
  * Platform you are using the C++ SDK on: Windows
  * Platform you are targeting: desktop

Hi,

We are new to google analytics implementation in Windows Desktop application.

As of Now, we didn't get any sample example of tracking Windows Desktop Application (WPF + C#) for google analytics.

Let us know, Is open-source from this repo will support for Windows Desktop Application(C# and WPF) ?

If yes, Please share the relevant information.

**Comment by DellaBitta** [comment]
Hi @DeepakHirapur,

Currently we do not support Analytics on Windows. [Check here for a list of the platforms that we support on desktop.](https://firebase.google.com/docs/cpp/setup?platform=ios#libraries-desktop).  

I'm going to close this issue for now, but please re-open it if you have any further questions. Thanks!
