### ISSUE TITLE
Not able to receive token from firebase server using cloud messaging test app using c++ sdk 

### ISSUE THREAD

**Issue by ravishelke536** [firebase/firebase-cpp-sdk#804]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: _____
  * Firebase C++ SDK version: 8.8.0
  * Main Firebase Components in concern: cloud messaging
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: Windows
  * Platform you are targeting: desktop

### [REQUIRED] Please describe the question here:
Hello,
        I am using firebase C++ SDK for desktop, trying to connect to firebase cloud.  I am using the cloud messaging sample app compiled using the cmake. As from log app is able to initialize the firebase object but while getting token using listener.PollRegistrationToken app stuck to this location. PollRegistrationToken does not return any error.

WARNING: Database URL not set in the Firebase config.
Initialized Firebase App.
Initialize the Messaging library
Try to initialize Firebase Messaging
Initialized Firebase Cloud Messaging.
Display permission prompt if necessary.
Finished checking for permission.
  ::firebase::messaging::Subscribe("TestTopic")...
::firebase::messaging::Subscribe("TestTopic") completed as expected
  ::firebase::messaging::Subscribe("!@#$%^&*()")...
ERROR: ::firebase::messaging::Subscribe("!@#$%^&*()") completed with error: 0, `Successfully completed as a stub.`

**Comment by DellaBitta** [comment]
Hi @ravishelke536,

The Firebase C++ SDK [supports Cloud Messaging on Android and iOS only](https://firebase.google.com/docs/cloud-messaging/cpp/client), and will not operate on a Desktop.  I'm sorry for any confusion!
