### ISSUE TITLE
[Bug] Crash when using RT DB on Windows if the username is not in English

### ISSUE THREAD

**Issue by QuyenKong** [firebase/firebase-cpp-sdk#805]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: _____
  * Firebase C++ SDK version: 8.6.0
  * Problematic Firebase Component: _____ (Auth, Database, etc.)
  * Other Firebase Components in use: Database(maybe)(Auth, Database, etc.)
  * Platform you are using the C++ SDK on:Windows(Mac, Windows, or Linux)
  * Platform you are targeting: _____ (iOS, Android, and/or desktop)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ?
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
I change my computer name to Thai language , example ยามิน  and when i start my application , it will be crash

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```
This is the report bug when my application crahsed

Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: ...(x86)\Early Start\Monkey Stories\MonkeyStories.exe
File: D:\a\firebase-cpp-sdk\firebase-cpp-...\level_d...gine.cc
Line: 307

Expression: false

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: ...(x86)\Early Start\Monkey Stories\MonkeyStories.exe
File: D:\a\firebase-cpp-sdk\firebase-cpp-...\level_d...gine.cc
Line: 307

Expression: false

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------

![Untitled](https://user-images.githubusercontent.com/57305649/148207416-50fbd862-8ef7-46a1-b981-0c661ccea872.png)

The application crashed when I change my computer user name to Thai language  like that  ยามิน
 
This problem is a hot bug in my project , please help me. Thank you. 

p/s: English is not my native language. I'm really sorry if i have any mistake.

**Comment by TruongBuixuan** [comment]
This issue happend with computer name using some accented language

**Comment by QuyenKong** [comment]
Do you have any ideal to solve this problem @TruongBuixuan  ???

**Comment by chkuang-g** [comment]
Excuse me to modify the title a bit.

And apologize for the inconvenience.

Quick question: Did you guy happen to open more than one instance of this standalone application? Or does it crashes when you launch only a single instance?

**Comment by chkuang-g** [comment]
Also, this seems to be related to persistence feature. A quick workaround is to turn off this feature with this function. Try to do so before creating any database instance.

https://firebase.google.com/docs/reference/cpp/class/firebase/database/database#classfirebase_1_1database_1_1_database_1a80516f5ad9bed9465098b07224fe4eda

**Comment by QuyenKong** [comment]
@chkuang-g  it crashes when i  launch only a single instance.

**Comment by QuyenKong** [comment]
> Also, this seems to be related to persistence feature.
> 
> **A quick workaround is to turn off this feature with `set_persistence_enabled(false)`.**
> 
> https://firebase.google.com/docs/reference/cpp/class/firebase/database/database#classfirebase_1_1database_1_1_database_1a80516f5ad9bed9465098b07224fe4eda
> 
> The only drawback to turn this off is offline access to the cached database. But this should prevent the crash.
> 
> ```
> Note: set_persistence_enabled() should be called before creating any instances of DatabaseReference, and only needs to be called once per application.
> ```

the app crashes when i launch only a single instance and it not work with me.
