### ISSUE TITLE
[Bug] DisconnectionHandler Future inside ValueListener's OnValueChanged never completes.

### ISSUE THREAD

**Issue by arslaanzafar** [firebase/firebase-cpp-sdk#813]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: Pre-built SDK from the website
  * Firebase C++ SDK version: 8.8.0
  * Problematic Firebase Component: Database
  * Other Firebase Components in use: Auth, Firestore
  * Platform you are using the C++ SDK on: Windows 
  * Platform you are targeting: Desktop

### [REQUIRED] Please describe the issue here:

If i have DisconnectionHandler inside OnValueChanged function of ValueListener, it's future never complete and times out, but outside DisconnectionHandler somewhere else works fine.

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Debug Logs:

DEBUG: [pc_0] Authentication success
DEBUG: [pc_0] Restoring outstanding listens
DEBUG: [conn_0] Sending data: {"d":{"a":"o","b":{"d":{"last_changed":"2022-01-13T18:27:00","state":"offline"},"p":"status/userid"},"r":3},"t":"d"}
DEBUG: [conn_0] Sending data: {"d":{"a":"o","b":{"d":{"last_changed":"2022-01-13T18:27:02","state":"offline"},"p":"status/userid"},"r":4},"t":"d"}
DEBUG: [conn_0] Sending data: {"d":{"a":"o","b":{"d":{"last_changed":"2022-01-13T18:27:02","state":"online"},"p":"status/userid"},"r":5},"t":"d"}
DEBUG: [conn_0] websocket message received
DEBUG: [conn_0] ProcessMessage (length: 43)
DEBUG: [conn_0] received data message
DEBUG: [pc_0] Trigger handler for request 3
DEBUG: [conn_0] websocket message received
DEBUG: [conn_0] ProcessMessage (length: 43)
DEBUG: [conn_0] received data message
DEBUG: [pc_0] Trigger handler for request 4
DEBUG: [conn_0] websocket message received
DEBUG: [conn_0] ProcessMessage (length: 43)
DEBUG: [conn_0] received data message
DEBUG: [pc_0] Trigger handler for request 5

Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
class ConnectionValueListener : public ValueListener
{
public:
    void OnValueChanged(const firebase::database::DataSnapshot& snapshot) override
    {
        bool status = snapshot.value().AsBool().bool_value();

        if (!status) {
            return;
        }

        auto res = databaseRef.OnDisconnect()->SetValue(isOfflineForDatabase);

        if (res.error() == firebase::database::kErrorNone) {
            res = databaseRef.OnDisconnect()->SetValue(isOnlineForDatabase);
            return;
        }
    }

    void OnCancelled(const firebase::database::Error& error_code, const char* error_message) override
    {
        LogMessage("ValueListener canceled: " + std::to_string(error_code) + error_message);
    }
};
```

**Comment by chkuang-g** [comment]
@arslaanzafar 

May I know how you learn that the future timeout?

If you try to access the future right after this line
```
auto res = databaseRef.OnDisconnect()->SetValue(isOfflineForDatabase);
```
The future is definitely not ready since it is an async operation.

Could you show us the code about what you mean by `outside DisconnectionHandler somewhere else works fine.`?

Thank you,
Shawn
