### ISSUE TITLE
[Question]  Upgrade Gradle version 

### ISSUE THREAD

**Issue by zimml** [firebase/firebase-cpp-sdk#857]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: (https://firebase.google.com/download/cpp)
  * Firebase C++ SDK version: 8.8.0
  * Main Firebase Components in concern: General
  * Other Firebase Components in use: General
  * Platform you are using the C++ SDK on: Windows/Linux
  * Platform you are targeting: Android

### [REQUIRED] Please describe the question here:

Hi, 

I'm using Firebase Cpp SDK for an hybrid application that targets Android / iOS / Windows / MacOS. For the Android version I notified that Firebase is still using Gradle 3.3.3. Is there some plane to update it to a newer version ? I ask that because with version < 4.1.0 we don't get any native debug symbols which would be of a great help to analyse crash occuring.

**Comment by a-maurice** [comment]
Hi, there isn't currently a plan to update the version, but that it is blocking native debug symbols is a good reason for it.  I'll switch this issue into a feature request, to track it.

**Comment by jonsimantov** [comment]
We've updated our Gradle version to 5.6.4.

Updating to 6.x and higher will involve fixing some breaking changes, so we have no plans to do so in the near future.
