### ISSUE TITLE
[Question]  firebase_messaging aar missing

### ISSUE THREAD

**Issue by zimml** [firebase/firebase-cpp-sdk#858]
### [READ] For Firebase Unity SDK question, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: (https://firebase.google.com/download/cpp)
  * Firebase C++ SDK version: 8.8.0
  * Main Firebase Components in concern: General
  * Other Firebase Components in use: General
  * Platform you are using the C++ SDK on: Windows/Linux
  * Platform you are targeting: Android

### [REQUIRED] Please describe the question here:

Hi,

I'm trying to add messaging on my android project but just realised the aar files are not generated for firebase_messaging. The messaging module is enabled in the CMake configurations. The static libraries (*.a) for messaging are correctly built but no trace of aar files. Am I missing something ? 

Note all other modules are working correctly only messaging is making the app crash at boot due to missing aar in apk.

**Comment by a-maurice** [comment]
So, the messaging aar is built through gradle, specifically this file: https://github.com/firebase/firebase-cpp-sdk/blob/main/messaging/messaging_java/build.gradle

We define a dependency on it here: https://github.com/firebase/firebase-cpp-sdk/blob/main/messaging/build.gradle#L87, which should trigger that build.  How are you hooking into the build?
