### ISSUE TITLE
[Bug] App Crashes when calling GetFile() from Storage with IOS 15

### ISSUE THREAD

**Issue by IamKingWaiMark** [firebase/firebase-cpp-sdk#881]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: Yes
  * Firebase C++ SDK version: 8.10.0
  * Problematic Firebase Component: Storage (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics, Auth (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: IOS 15 (iOS, Android, and/or desktop)

### [REQUIRED] Please describe the issue here:

App Crashes when Downloading file from Storage with IOS 15

#### Steps to reproduce:

Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ?
Only tested with Unreal Engine C++

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

What happened? How can we make the problem occur?
Not sure. 
Just call the GetFile function.

#### Relevant Code:

```
	StorageReference.GetFile(LocalPath, StorageListener).OnCompletion(
		[OnDownloaded, OnFailToDownload](const firebase::Future<unsigned long>& Result)
		{
			if(Result.error())
			{
				
			}
			else
			{
				
			}
		}
	);
```

**Comment by chkuang-g** [comment]
@IamKingWaiMark 

Thank you for reporting this.  Are you able to provide the callstack when it crashes?

You should be able to use `llvm` from Xcode.  When it crashes, bring up `llvm` and use the following commands.
```
# Callstack from the current crashing thread.
bt

# Callstack from every thread
bt all
```

Also, could you verify if it crashes with iOS 14 or with the emulator as well?

Thank you
