### ISSUE TITLE
[Question] linking error for firebase::FutureBase in release mode

### ISSUE THREAD

**Issue by ArthurKValladares** [firebase/firebase-cpp-sdk#888]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp)
  * Firebase C++ SDK version: 8.10
  * Main Firebase Components in concern: Remote Config
  * Other Firebase Components in use: Analytics
  * Platform you are using the C++ SDK on: Mac
  * Platform you are targeting: iOS

### [REQUIRED] Please describe the question here:
 I'm integrating Firebase RemoteConfig into my app, and everything works as expected in debug mode. However, when building in release mode I'm getting undefined symbol errors:
```
Undefined symbols for architecture arm64:
  "firebase::FutureBase::error_message() const", referenced from:
      ...
  "firebase::FutureBase::OnCompletion(void (*)(firebase::FutureBase const&, void*), void*) const", referenced from:
      ...
  "firebase::FutureBase::error() const", referenced from:
      ...
ld: symbol(s) not found for architecture arm64
```
I'm having some trouble understanding why this would be, especially since the behavior only happens when building with optimizations. My Podfile looks like:
```
target '...' do
platform :ios, '10.0'
  # Pods for jumbline_iOS
  pod 'Firebase/Analytics', '8.13'
  pod 'Firebase/RemoteConfig', '8.13'
end
```
and I am linking the frameworks:
`firebase.xcframework, firebase_analytics.xcframework, and firebase_remote_config.xcframework` and I have added the `GoogleService-Info.plist` file to my project. I'm assuming something in my setup is incorrect and causing this issue, but I'm having a hard time pinpointing what exactly.

**Comment by jonsimantov** [comment]
When you drag in the xcframework files, did you check the box in Xcode to copy frameworks into the build directory? It's possible Xcode can't find the framework files if they aren't where it expects.

If so, could you try the Remote Config [quickstart](https://github.com/firebase/quickstart-cpp/tree/master/remote_config/testapp) or [integration test](https://github.com/firebase/firebase-cpp-sdk/tree/main/remote_config/integration_test) and see if you have a similar issue on iOS after following the readme instructions?

**Comment by ArthurKValladares** [comment]
I'm running a pretty esoteric setup where I'm calling the library from Rust bindings, and I've narrowed the problem down to something in the setup erroneously causing the `FutureBase` functions to be erroneously removed during dead code elimination. All that to say, this is definitely not a problem on your end so I will just close this issue. Thank you for the help, and sorry for the unhelpful issue 😬 .
