### ISSUE TITLE
FR: Bazel/Blaze BUILD 

### ISSUE THREAD

**Issue by cpsauer** [firebase/firebase-cpp-sdk#930]
Hey Googlers!

Any chance you'd be down to release the Blaze/Bazel (Blazel!) BUILD files for this code? I assume you've got em internally from seeing old commits. They would be very handy for those of us building with Bazel.

Thanks for your consideration!
Chris
(ex-Googler)

**Comment by AlmostMatt** [comment]
Hi Chris,

As I understand it, this is not feasible.

The internal blaze BUILD files have dependencies on other internal google packages and build infrastructure, so on their own they would not be functional. Additionally, there are some feature differences between blaze and bazel which factored into the decision to use CMake when building from the GitHub repository.

**Comment by cpsauer** [comment]
Oh bummer. If not for building from source, would it be feasible to track adding Bazel wrappers for using the prebuilt libraries?

(I'll write my own, but it seems like it could be good to collaborate!)

One side note that I've encountered so far: Putting the binary release on GitHub would be handy for folks using auto-updaters that hit the GitHub API! (Like those used with Bazel.)
