### ISSUE TITLE
[Bug] Inconsistencies about Dependencies

### ISSUE THREAD

**Issue by cpsauer** [firebase/firebase-cpp-sdk#947]
Hey wonderful Firebase folks,

Looks like there are some inconsistencies in the dependencies listed in various places. Could I ask you to clarify what's right?

As an example: Look at Analytics in the [release readme](https://github.com/firebase/firebase-cpp-sdk/blob/792395e7e4af75f3369386cf011bc53065831534/release_build_files/readme.md) vs. [firebase_dependencies.gradle](https://github.com/firebase/firebase-cpp-sdk/blob/792395e7e4af75f3369386cf011bc53065831534/release_build_files/Android/firebase_dependencies.gradle). (Both those links are for HEAD at the time of writing.)

You'll notice that for maven, the readme references only com.google.firebase:firebase-analytics (and says Google Play Services is not required), but firebase_dependencies.gradle also lists "com.google.android.gms:play-services-base" as a dependency.

That's just the first one that popped out to me--I'd guess there might be more? Maybe worth a broader fix? But also if you know what's right for Analytics, I'd love to hear.

Thanks so much for all you do!
Chris
(ex-Googler)

P.S. This came up while wrapping things for use from Bazel. For more context see #930 
P.P.S.: Not following the template for directness and friendliness, since this isn't a code issue you're going to have trouble reproducing. Instead, I'll just link directly to the relevant docs/source.

**Comment by jonsimantov** [comment]
Hmm, you might be right that the Analytics dependency doesn't actually need play-services-base (it may have in the past). I'll try removing it and see whether our tests still work.

It would definitely be cleaner to switch over to [Android Bill-of-Materials](https://firebase.google.com/docs/android/learn-more#bom), which provides a single version number for the Firebase Android SDK instead of individual version numbers for each dependency.

**Comment by cpsauer** [comment]
Thanks, Jon! So to confirm, then, you wouldn't anticipate play-services-base being required for the standard initialization in the docs https://firebase.google.com/docs/analytics/cpp/start#create_and_initialize_the_firebase_app?

**Comment by jonsimantov** [comment]
> Thanks, Jon! So to confirm, then, you wouldn't anticipate play-services-base being required for the standard initialization in the docs https://firebase.google.com/docs/analytics/cpp/start#create_and_initialize_the_firebase_app?

Actually, looking further into this, it does look like we are currently require play-services-base in all situations (it just so happens that many Firebase Android libraries already depend on it for you).

I'm considering this a bug - a fix is in #953, and the BoM update is in #949.

**Comment by a-maurice** [comment]
This should be fixed in the previous C++ release, available here: https://github.com/firebase/firebase-cpp-sdk/releases/tag/v9.1.0
