### ISSUE TITLE
[General Question] Conflicts between Firebase SDK and WebRtc SDK | ssl_lib.cc multiple definitions of functions

### ISSUE THREAD

**Issue by Mian-Zaid** [firebase/firebase-cpp-sdk#989]
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: _____
  * Firebase C++ SDK version: **_9.0.0____**
  * Main Firebase Components in concern: __App___ (Auth, Database, etc.)
  * Other Firebase Components in use: __Database___ (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: __Ubuntu 18.04.6 LTS___ (Mac, Windows, or Linux)
  * Platform you are targeting: **_Desktop____** (iOS, Android, and/or desktop)

### [REQUIRED] Please describe the question here:

I am building Firebase Sdk with WebRtc. while adding firebase App classes I am getting the following error. 

`home/webrtc/lib_webrtc/src/third_party/boringssl/src/ssl/ssl_lib.cc.o first defined here`

`../firebase/libs/linux/x86_64/legacy/libfirebase_app.a(93f69bbf5771d4a5b72056dec59d993b_ssl_lib.cc.o): In function ssl_st::~ssl_st()':`

`/home/runner/work/firebase-cpp-sdk/firebase-cpp-sdk/out-sdk/external/src/boringssl/src/ssl/ssl_lib.cc:655: multiple definition of ssl_st::~ssl_st()'`

getting the same error for every function of `ssl_st` 

Stand-alone Both firebase SDK and Webrtc SDK are working fine, the above error arises upon integrating these two.

here are my [CMakeLists.txt](https://github.com/firebase/firebase-cpp-sdk/files/8898645/CMakeLists.txt)

**Comment by chkuang-g** [comment]
Are you able to build from source?  That should work around with this issue.

If not, we should have a fix in the next release.
https://github.com/firebase/firebase-cpp-sdk/pull/1000

**Comment by Mian-Zaid** [comment]
> Are you able to build from source? That should work around with this issue.
> 
> If not, we should have a fix in the next release. #1000

No i haven't

**Comment by jonsimantov** [comment]
This should be fixed in the [latest release](https://github.com/firebase/firebase-cpp-sdk/releases/tag/v9.4.0).
